### ISSUE TITLE
How about an intro post on Gopher Academy

### ISSUE THREAD

**Issue by bketelsen** [starkandwayne/shield#10]
Been watching with anticipation.  How about an introductory post on Gopher Academy's much read December Blog Post series?  https://docs.google.com/spreadsheets/d/1H0rj7TJo0t8GWyNdGwEc6bGcDj6UgJUN42JtAtbPMrk/edit?usp=sharing

**Comment by qanx** [comment]
Sure - we claimed a spot and will spin something up :)

**Comment by bketelsen** [comment]
awesome!
