### ISSUE TITLE
API Authentication & Authorization

### ISSUE THREAD

**Issue by jhunt** [starkandwayne/shield#104]
The SHIELD API really needs to handle authentication by either of the following methods:

1. **Single-User (root) Authentication**, whereby a username and password are supplied as configuration to the shield daemon and it performs HTTP Basic (or Digest) authentication.  Authorization is not performed; all capabilities are afforded the root account.
2. **OAuth2 Integration**, whereby authentication and authorization are handled by a third-party authentication provider like Github or Cloudfoundry UAA.

Some thoughts on implementation:

The CLI needs to be able to handle either, using a protected, per-user file to store credentials or tokens.  Multiple SHIELD targets should be usable from a single file, à la BOSH CLI.

The BOSH Release for SHIELD will need new properties for configuring OAuth2 and SUA (Single-User Authentication).

OAuth2 configuration **must** take precedence over SUA if both are configured.

A default SUA configuration of `username: admin` and `password: admin` is allowable, if desired.  This should be done at the `shieldd` level, not necessarily the BOSH release (this allows local testing without a full deployment)

Ref:
- https://blog.starkandwayne.com/2014/11/11/simple-golang-oauth-client-for-cf/
- https://blog.pivotal.io/pivotal-cloud-foundry/products/how-to-integrate-an-application-with-cloud-foundry-using-oauth2

**Comment by jhunt** [comment]
@geofffranks I think this is done now?

**Comment by geofffranks** [comment]
Correct, authentication + oauth + uaa + github are handled now.
