### ISSUE TITLE
Allow cli not to use regex when trying to list object

### ISSUE THREAD

**Issue by longnguyen11288** [starkandwayne/shield#112]
Currently if we do list store its a regex for name and cli returns multiple results, can we have `shield --raw list store s3` only match exact name vs regex matching with %

Log example for command above.
```
2016-02-22 15:29:16.647966763 +0000 UTC shieldd: DEBUG: Parameters: [%s3%]
2016-02-22 15:29:23.463956501 +0000 UTC shieldd: DEBUG: Executing SQL:
            SELECT s.uuid, s.name, s.summary, s.plugin, s.endpoint, -1 AS n
                FROM stores s
                WHERE s.uuid = s.uuid AND s.name LIKE $1
                ORDER BY s.name, s.uuid ASC
```

**Comment by thomasmmitchell** [comment]
Reopening this issue because this behavior is only needed for other commands - so far I've discovered `show target` and `edit target` need to exact match with `--raw` enabled.
