### ISSUE TITLE
Allow Postgres plugin to backup specific database 

### ISSUE THREAD

**Issue by mrferris** [starkandwayne/shield#132]
Proposing that we use the existing postgres plugin to handle this new functionality.
Putting a `pg_database` key in the JSON configuration for the plugin. If this key is not entered or left empty, the plugin will default to its current 'dumpall' functionality. 
If this key is entered, the plugin will only dump the database specified.

**Comment by geofffranks** [comment]
Can we make the key `pg_database`, to follow the naming convention used in the `mysql` plugin?

**Comment by jhunt** [comment]
Merged.
