### ISSUE TITLE
The button on the left of backups should direct to a page showing what it is doing

### ISSUE THREAD

**Issue by xiujiao** [starkandwayne/shield#137]
Restore job is done when we click the button, need to show this info when we click the button

**Comment by jhunt** [comment]
We discussed a few options:

1. Providing a notifier-based feedback message at the top of the screen (similar to create/update/delete ops)
2. Dropping the "restore" icon entirely on the table view, and using a popup table similar to tasks to show more details (incl. notes) about the archive and a button for restore.

**Comment by jhunt** [comment]
I believe we handled this in #225
