### ISSUE TITLE
CLI won't allow Invalid (self-signed) SSL certificates

### ISSUE THREAD

**Issue by thomasmmitchell** [starkandwayne/shield#150]
Now that authentication has been added, it wants to verify signed certificates, which can make developing on a local platform cumbersome, as Shield rejects incoming requests from the CLI.

The cli probably needs something like a skip-ssl-validation flag.

**Comment by jhunt** [comment]
https://github.com/starkandwayne/shield/blob/master/cmd/shield/main.go#L50

```
$  shield -h 2>&1 | grep -A1 skip-ssl
 -k, --skip-ssl-validation
                    Disable SSL Certificate Validation
```
