### ISSUE TITLE
Client-Driven Backups

### ISSUE THREAD

**Issue by karampok** [starkandwayne/shield#179]
Hi,
we are looking to use shield for supporting backup creation in a client-driven way.

This means that 
1.  a target will be defined
2.  a backup will be triggered for that target (e.g. from a web app) 
3. an http call will be made to shield 
4. then  we should be able to check the status of the backup,
5. finally to have a link for that archive for future restores

Ideally we would like to have only retention, a target and a one-time job that runs instantly once (the single call). Scheduler should not be defined in that process.

Some reverse process should take place in restore. For example when you trigger a restore you do not know when is finished (or if finished)

Is this something that could be integrated in shield?

Thx

**Comment by jhunt** [comment]
This will be handled in multi-tenancy; see [docs/tenancy.md](/starkandwayne/shield/blob/master/docs/tenancy.md)
