### ISSUE TITLE
Restoring mysql databases doesn't work when using --all-databases

### ISSUE THREAD

**Issue by bodymindarts** [starkandwayne/shield#211]
Trying to backup + restore _all_ databases of an rds cluster. We have configured the mysql plugin. Backing up seems to work fine but when restoring we get an error.
The `mysql` command doesn't seem to recognize the `--all-databases` option that gets set [here](https://github.com/starkandwayne/shield/blob/master/plugin/mysql/plugin.go#L201)

We can recreate the problem manually as follows:
```
# on host with shield agent
cd /var/vcap/packages/shield-mysql/bin
export MYSQL_PWD=<password>
./mysqldump --all-databases -h <endpoint> -P 3306 -u admin > /tmp/rds.out
./mysql --all-databases -h <endpoint> -P 3306 -u admin <(cat /tmp/rds.out )               
./mysql: unknown option '--all-databases'
```

**Comment by jhunt** [comment]
Tested the fix in the lab.  Hoping to cut a release this week.
