### ISSUE TITLE
Usage and set up guide

### ISSUE THREAD

**Issue by abhilash07** [starkandwayne/shield#213]
Hi is there any usage setup guide for shield i am new to shield i have understand the concept but it is little bit confusing i am looking for beginner documentation of shield. Thanks in advance

**Comment by jhunt** [comment]
We don't have anything to my knowledge, but it definitely sounds like a great idea. I'll see what we can put together!

**Comment by abhilash07** [comment]
Dear James Hunt, Good morning,

Thanks for your email, yes you're right because for beginners its very
difficult to understand how to use shield. Thanks in advance. Have a good
day.

Regards

Abhilash S

**Comment by jhunt** [comment]
I believe @johnlonganecker is working on this, as part of your other ticket, #251, so I'm going to close this one as a duplicate.
