### ISSUE TITLE
Trigger failures in store plugins when no data is received

### ISSUE THREAD

**Issue by geofffranks** [starkandwayne/shield#215]
Add catch-all functionality to cause store plugins to error out if they detect no data inbound from stdin to actually store on the filesystem.

This will help counteract situations where target plugins exit non-zero but do not provide any data to be backed up to stdout

**Comment by jhunt** [comment]
I _think_ this is as simple as interposing a `| tee >(head -c1 > $some_tmpfile)` into the pipeline here: https://github.com/starkandwayne/shield/blob/master/bin/shield-pipe#L102

And then checking to make sure that `$some_tmpfile` is not zero-length (it should have exactly one byte in it).

I'll take a crack at this later today / tomorrow.
