### ISSUE TITLE
UI Improvement

### ISSUE THREAD

**Issue by cweibel** [starkandwayne/shield#225]
On the Backups tab of the web ui there is an icon in the left most column of the table which allows you to perform a restore.  To perform the restore you simply click the icon. 

The issue is:

- There is no column header to indicate the column is for restore
- There is mouse over to know what the button does
- There is no "Are you sure?"-like prompt when launching a restore like there is when deleting a backup file
- There is no prompt letting the user know a restore was launched

**Comment by cweibel** [comment]
I'd love to pair with whoever wants to fix this

**Comment by jhunt** [comment]
Will do, @cweibel

**Comment by jhunt** [comment]
We totes did this by the way.
