### ISSUE TITLE
Task timeouts

### ISSUE THREAD

**Issue by geofffranks** [starkandwayne/shield#23]
Add support to shield to time-out tasks and mark them as failed if they take too long.

If a job gets scheduled but has something currently marked as running, fail that running job, with a message about a timeout occurring, prior to starting the new job. If possible, retain any of the stdout/stderr of the job that is being timed out, and append on the timeout message, storing it all in the task log. Use the 'failed' state. Ensure that a task timeout error also shows up in the shield log, in case anything is parsing that log for failure messages + monitoring

**Comment by qanx** [comment]
Resolved in commit b4cef09
