### ISSUE TITLE
Drop use of minio-go library

### ISSUE THREAD

**Issue by geofffranks** [starkandwayne/shield#230]
We should find another library for our s3 and scality plugins. minio-go made this change: https://github.com/minio/minio-go/commit/a0a13a2873c249ca89c7b6a0df2ff041577e1bac which results in the following:

1) Confusion as to whether we're using HTTP or HTTPS for our s3/scality connections (we are, unless we update the library)
2) A ticking time-bomb for when someone updates minio-go to a newer version, whereby all our connections silently become http instead of https.

Also, we had to fork minio-go for scality support (https://github.com/starkandwayne/minio-go/commit/37621e4e914c3e2e50bf6827d072c0affd6086ae). We should make sure that whatever replacement we go with doesn't regress that fix

**Comment by thomasmmitchell** [comment]
The limiting factor here is S3 v2 support. We could theoretically edit that fork for use with both the s3 and scality plugins.

**Comment by geofffranks** [comment]
Also need to take into consideration that we had to modify minio for things related to block upload sizes + part counts, for use on scality: https://github.com/starkandwayne/minio-go/commit/37621e4e914c3e2e50bf6827d072c0affd6086ae

**Comment by jhunt** [comment]
I wrote an s3 library that does _exactly_ what we need, available in the v8 version of s3.  Also, the scality plugin has been deprecated since I was able to move the scality-specific behavior into the s3 plugin itself.  WIN!
