### ISSUE TITLE
Add --single-transation and --quick options to mysql plugin

### ISSUE THREAD

**Issue by yatzek** [starkandwayne/shield#236]
These mysqldump options can be useful for backing up larger databases:
http://dev.mysql.com/doc/refman/5.7/en/mysqldump.html#option_mysqldump_single-transaction
http://dev.mysql.com/doc/refman/5.7/en/mysqldump.html#option_mysqldump_quick

**Comment by janaurka** [comment]
I guess it would simply be great if there would be something like a option:

```
{
"mysql_user":"username-for-mysql",
"mysql_password":"password-for-above-user",
"mysql_host":"hostname-or-ip-of-mysql-server",
"mysql_port":"port-above-mysql-server-listens-on",
"mysql_read_replica":"hostname-or-ip-of-mysql-replica-server",  #OPTIONAL
"mysql_database": "your-database-name",  #OPTIONAL
"mysqldump_settings":"" #DOES NOT EXIST YET
}
```

Where `mysqldump` specific stuff could land.

For example the `--singe-transaction` or a `-f` (which is basically a problem I have right now. Some users have `views` on non existing users which breaks `mysqldump` which aborts the whole backup process :( )
