### ISSUE TITLE
Re-run pending tasks

### ISSUE THREAD

**Issue by geofffranks** [starkandwayne/shield#24]
Currently Shield does not do anything with tasks that never come out of the pending state. To address this:

Add a function to ReschedulePendingTasks:
- Find all tasks in the database listed as pending.
- Cross-reference those tasks with the tasks in the scheduling queue of the supervisor. If there is a database-found task which is not in the scheduling queue, add it to the queue

Call this function at startup

**Comment by filefrog** [comment]
This requires changes to the schema (hello, v3!) to track more important information about Task objects (like, what they are supposed to be doing).
