### ISSUE TITLE
Support alternative exit codes for mysql plugin

### ISSUE THREAD

**Issue by janaurka** [starkandwayne/shield#240]
Hey

This is a feature request.

It would be great if the `mysql` plugin would support variable `exit codes`. Currently it will fail on an `exit code != 0`, which should be fine most of the time.

The problem is that you (as DB operator and in charge of backups) are not always capable of having a proper state in each `dbs`.  For example: We have a case where we have some `VIEWS` which belong to a not anymore existing user in a `dev` db. The Devs don’t really care, but `mysqldump` fails to backup the db.

That’s why I’ve created https://github.com/starkandwayne/shield/pull/239 . Unfortunately this solves only one part of the puzzle. With https://github.com/starkandwayne/shield/pull/239 we’d be able to tell `mysqldump` to `--force` and ignore the erros, _but_ `mysqldump` then will escape with a `non-zero` exit code (in our case it’s `2`) which will be evaluated as a `failed backup` by `shield`.

`shield` comes prepared to respect other `exit codes` but the `mysql` plugin needs some changes to make this also possible there. I’ve started working on the implementation here: https://github.com/janaurka/shield/tree/exit_codes .

_Note:_ Next to the `exit codes` the `mysql` plugin needs to be refactored to use `ExecWithOptions` instead of `Exec` (which is already done in https://github.com/janaurka/shield/tree/exit_codes).

I experienced a problem with validating the `exit codes` which are expected as `[]int` like `[]int{0,2}`, which would allow `exit codes` `0` and `2`.

There is https://github.com/janaurka/shield/blob/exit_codes/plugin/endpoint.go#L99 which allows `[]interface` and i’ve added https://github.com/janaurka/shield/blob/exit_codes/plugin/endpoint.go#L112 which would allow to set a `default` (here it would be `[]int{0}`), but the `go compiler` complains about:

```
(type []int) as type []interface {} in argument to endpoint.ArrayValueDefault
```

Which is probably because of https://github.com/golang/go/wiki/InterfaceSlice. (But my `go` skills are to immature to solve the problem atm :( .

Maybe if you point me towards the right direction, I’d be able to fully implement this on my own. I’ve also tried to ask on the [Slack channel](https://cloudfoundry.slack.com/archives/shield/p1483622488000008).

cheers
j

**Comment by jhunt** [comment]
I'm not really sure what the real nature of the feature request is.  Does it make more sense to just not enforce exit code checking if the operator so wishes?  I.e., something like:

```
{
  "mysql_user":     "username",
  "mysql_password": "secret",
  "strict_mode":    "no"
}
```

and then if `strict_mode` is `no`, don't worry about the exit codes for normal exits?

I'm dubious about forcing operators to whitelist _specific_ exit codes, unless those codes are standard, and documented somewhere (which I have rarely found to be the case, with MySQL/MariaDB, or any other software project/product)

**Comment by janaurka** [comment]
@jhunt: yeah that would be a good solution for me as well. I ACK on the poor documentation of exit codes.

**Comment by jhunt** [comment]
I think we'll go with that change then, since it is far simpler.

**Comment by jhunt** [comment]
Hey @janaurka is this still something you want / need?

**Comment by janaurka** [comment]
Hey @jhunt . Nope, we don’t need that anymore. Will close the issue
