### ISSUE TITLE
Prometheus exporter to allow alerting for failed backups

### ISSUE THREAD

**Issue by yatzek** [starkandwayne/shield#242]
Would be nice to integrate shield with an alerting tool like Prometheus (https://github.com/cloudfoundry-community/prometheus-boshrelease)

**Comment by frodenas** [comment]
@yatzek Check the [shield_exporter](https://github.com/cloudfoundry-community/shield_exporter). The latest version of the [Prometheus BOSH release](https://github.com/cloudfoundry-community/prometheus-boshrelease/commits/master) already ships this exporter alongside some dashboards and alerts.

**Comment by yatzek** [comment]
Huh, lovely! Closing the issue.
