### ISSUE TITLE
SHIELD Agent SSH Key Failure when co-located with daemon

### ISSUE THREAD

**Issue by jrbudnack** [starkandwayne/shield#244]
If the Agent and the Daemon are co-located on the same host, the agent will create a blank "authorized_keys" file if it starts before the daemon.  The agent should not be allowed to create a blank file and should fail, so that it can try to start again once Monit successfully starts the daemon.

**Comment by jhunt** [comment]
Migrated to https://github.com/starkandwayne/shield-boshrelease/issues/68
