### ISSUE TITLE
how to backup & restore Bosh Deployments and core Cloud Foundry internal services

### ISSUE THREAD

**Issue by abhilash07** [starkandwayne/shield#251]
Hi everyone i have been working on shield backup and restore past three weeks it is awesome service to backup and restore bosh deployments thanks to starkandwayne. As a beginner using the shield i am, successful in backup & restore  non-core Cloud Foundry services  (PostgreSQL). But unfortunately i have no idea how to backup cor Cloud Foundry internal services and any Bosh Deployments. If any documentation available please do need full help (or) any information is available please provide us. Thanks in advance.

Thank You
Best Regards

Abhilash S

**Comment by wayneeseguin** [comment]
Hi Abhilash!!! It is definitely possible, it needs documentation. We'll get someone to look into publishing some documentation about it.

**Comment by abhilash07** [comment]
Hi wayn thanks for your quick reply, thank you so much for your information hope to see your publishment soon. Have a good day. Thanks in advance.

Thank You
Best Regrads

Abhilash S

**Comment by jhunt** [comment]
@johnlonganecker any forward progress on this?

**Comment by johnlonganecker** [comment]
I believe it got reassigned @norman-abramovitz and/or @7hunderbird do you remember?

**Comment by dinomiteX** [comment]
Hey @jhunt,
are you still working on a "getting started" guide?

**Comment by jhunt** [comment]
I am, as part of the v8 launch
