### ISSUE TITLE
Code cleanup: Isolate constants for code consistency.

### ISSUE THREAD

**Issue by norman-abramovitz** [starkandwayne/shield#257]
The binary path for the database binaries are hard coded into the code. It would cleaner and easier to change if they were made into a constant and that constant is referenced.

The mongodb isolated some constants instead of hardcoding them into the function calls.   

var (
	DefaultHost        = "127.0.0.1"
	DefaultPort        = "27017"
	DefaultMongoBinDir = "/var/vcap/packages/shield-mongo/bin"
)

This should be done for the other plugins as well.

**Comment by jhunt** [comment]
A better solution is to migrate pathing concerns into the BOSH deployment for shield-agent, and remove the hard-coded paths from the endpoints.

**Comment by norman-abramovitz** [comment]
Good idea
