### ISSUE TITLE
mysql plugin: restore with SET SESSION SQL_LOG_BIN=0 (Disabling binary logging when restoring a MySQL dump)

### ISSUE THREAD

**Issue by GETandSELECT** [starkandwayne/shield#258]
Hi 

Please restore mysqldump with SQL_LOG_BIN=0
It's a huge performance difference when restoring big database.

example http://dba.stackexchange.com/questions/165617/disabling-binary-logging-when-restoring-a-compressed-mysql-dump

**Comment by johnlonganecker** [comment]
With the mysql plugin you can specify mysql flags/options in the configuration JSON.

`mysql --init-command=str` - `SQL statement to execute after connecting to the server.`
https://dev.mysql.com/doc/refman/5.5/en/mysql-command-options.html#option_mysql_init-command

Can you try this in your shield plugin config:
```
{
...
    "mysql_options"      : "--init-command=\"SET SESSION sql_log_bin=0;\"",
...
}
```

**More information on the plugin Configuration**
https://godoc.org/github.com/starkandwayne/shield/plugin/mysql

I am not a MySQL expert but let me know if this does the trick. Thanks!

**Comment by jhunt** [comment]
Are there any instances where you would want to explicitly _not_ do this?  Otherwise, I'm fine with prepending the `SET ...` statement to the SQL as it gets restored.  If there are cases where one ought not do that, having a plugin config option for it seems reasonable, i.e.:

```
{
  "enable_bin_log": "yes"
}
```

**Comment by GETandSELECT** [comment]
I can't imagine a restore situation where you wish bin_log.

@johnlonganecker 

I enabled already mysql_options. Those are during dump (mysqldump)?

```
          mysql_options: --single-transaction --routines --events --max_allowed_packet=1G
            --flush-logs --master-data=2

```

**Comment by jhunt** [comment]
I believe #403 takes care of this, I need to set up a live playground of data systems to test with, since I don't want to invoke the Phalanx just for this.
