### ISSUE TITLE
xtrabackup plugin failing at restoring old cf-mysql deployments

### ISSUE THREAD

**Issue by bgandon** [starkandwayne/shield#260]
The `xtrabackup` binary version `2.2.10` shipped by the cf-mysql release `v26` doesn't support the `--move-back` option on which the xtrabackup SHIELD plugin relies.

In such situation, the `xtrabackup` job of the shield-boshrelease is supposed to help. Unfortunately, it brings an `xtrabackup` package whose name conflicts with the one already installed by the `mysql` job of the cf-mysql release.

A solution for the xtrabackup SHIELD plugin would be to implement differently the simple “move” operations that the `--move-back` options performs.

Here is how the operation would look if written in shell.
```
monit stop all
rm -rf /var/vcap/store/mysql
mv /tmp/backups /var/vcap/store/mysql
chmod 755 /var/vcap/store/mysql
chown -r vcap:vcap /var/vcap/store/mysql
monit start all
```

As you see, there is a second issue here: doing this “move back” operation requires the mysql backend to be shut down, whereas `emergency-recovery` for instance just restarts it after the `xtrabackup restore` is performed via `shield-pipe`.

Question: is it possible for a SHIELD plugin to temporarily stop a monit job while a backup archive is being restored?

**Comment by jhunt** [comment]
Would renaming the SHIELD package for `xtrabackup` take care of the issue without interfering with `monit`?

**Comment by jhunt** [comment]
My question was in response to:

> Question: is it possible for a SHIELD plugin to temporarily stop a monit job while a backup archive is being restored?

Do we even need to investigate this if we just rename the package?

**Comment by szaouam** [comment]
Hello @jhunt ,
When i tried to use the xtrabackup with mysql i got :

> Error 80011: Package name collision detected in instance group 'mysql_z1': job 'cf-mysql/mysql' depends on package 'cf-mysql/xtrabackup', job 'shield/shield-agent' depends on 'shield/xtrabackup'. BOSH cannot currently collocate two packages with identical names from separate releases.

I think that we need to have another name for this package.

Best regards,

**Comment by jhunt** [comment]
I'll see what we can do around renaming this to something more SHIELD-specific to avoid the naming conflicts.

**Comment by jhunt** [comment]
@gogolok any concerns merging the `xtrabackup`+`mariadb` packages together and replacing the `shield-mysql` package outright?  IIRC, you are the primary user of MySQL stuff...

**Comment by gogolok** [comment]
@karampok Can you comment?

**Comment by xanderrman** [comment]
@karampok @gogolok just wanted to check in on the progress of this

**Comment by jhunt** [comment]
These have been moved into addon BOSH releases in v8 (see https://github.com/shieldproject/?q=addon) which should help with package naming conflicts.

**Comment by bgandon** [comment]
Ok, cool.
Nice to see this new Github Org and website!
