### ISSUE TITLE
Deleting an archive doesn't remove it from store

### ISSUE THREAD

**Issue by bgandon** [starkandwayne/shield#261]
Whether deleting an archive using the web UI or using the CLI, the command just deletes the archive reference from the database, and doesn't actually purge the archive from the store. Then the purge must be done manually, but without its exact key, it might be hard to find in the store.

Is this by design? If yes, then for which reason?

Would it be possible to add a CLI switch that would allow to also purge the archive from the store?

**Comment by jhunt** [comment]
This is an oversight on the supervisor.  We should not allow removal of the archive from the database until it has been purged, and we should allow purgation via the CLI.

**Comment by jhunt** [comment]
v8 now longer deletes archives from the database, but does schedule purge tasks.
