### ISSUE TITLE
db.GetAllJobs is broken after "Job Health Checks" commit (1bee6f3bc9891cac8bbc7a0e6962a550546856c5)

### ISSUE THREAD

**Issue by yatzek** [starkandwayne/shield#262]
Left join to tasks table results in the same job being scheduled many times, as many times as the given job
was run: https://github.com/starkandwayne/shield/blob/master/db/jobs.go#L107

**Comment by jhunt** [comment]
Bollocks.  Will look at this ASAP.

**Comment by szaouam** [comment]
Same problem, 

![duplicated](https://cloud.githubusercontent.com/assets/22029437/23858111/b2e2f9e4-07ff-11e7-92a6-0be9fbf56b90.JPG)

**Comment by jhunt** [comment]
Yeah.  @yatzek and @szaouam you will need to roll back a release.

**Comment by jhunt** [comment]
I've got a revert working its way through the pipeline as we speak.

**Comment by jhunt** [comment]
vis. https://ci.starkandwayne.com/teams/main/pipelines/shield

**Comment by yatzek** [comment]
Cool, thanks a super quick reaction. Any chance for a new release of shield-boshrelease?

**Comment by jhunt** [comment]
Once `master` works its way through unit tests and phalanx, we'll cut a new 0.6.x release, and pull back the bad one.

**Comment by jhunt** [comment]
I'm also trying to assemble a process around having the dev team run a long-lived SHIELD and do the operational day-to-day so these kinds of things gets caught sooner (ideally, before we hit that "shipit" button)

**Comment by norman-abramovitz** [comment]
Does it make sense to use a the distinct keyword to eliminate the duplicates?

**Comment by jhunt** [comment]
@norman-abramovitz we will look at a fix for the original functionality later.  The pressing issue at hand is (a) getting a good release without the bad behavior out and (b) fixing the large hole in our release process.

**Comment by jhunt** [comment]
6.6.2 is out, give it a whirl.

**Comment by jhunt** [comment]
@yatzek / @szaouam any joy?

**Comment by yatzek** [comment]
seems to be working ok, thanks.

**Comment by szaouam** [comment]
@jhunt nice work. it is working well . Thank you.

**Comment by jhunt** [comment]
@szaouam / @yatzek - @cweibel and I just cut SHIELD BOSH 6.7.0, which attempts to re-instate this functionality with a steadier hand.  We're going to run that version internally for a few days just to be on the safe side.
