### ISSUE TITLE
Using postgres plugin without pg_password

### ISSUE THREAD

**Issue by szaouam** [starkandwayne/shield#263]
Hello,

I am using the shield bosh release to perform a backup for all databases.

I am performing the backup using the "vcap" user without a pg_password. 

I am not able to use the postgres plugin without setting up a pg_password. 

> Validating TARGET plugin `postgres`...
======================================
✓ pg_host      127.0.0.1
✓ pg_port      5524
✓ pg_user      vcap
✗ pg_password  No 'pg_password' key specified in the endpoint json
✓ pg_database  none (all databases will be backed up)
postgres: invalid configuration

To avoid this error, i set up the plugin configuration with an empty pg_password (pg_password:"") .

What about having a default value (an empty string) for pg_password ?

Best regards,

**Comment by jhunt** [comment]
I'd rather not, Did the empty password string work for you?

**Comment by szaouam** [comment]
@jhunt yes it work for me, thank you.
