### ISSUE TITLE
Fail when connection to s3 fails

### ISSUE THREAD

**Issue by janaurka** [starkandwayne/shield#266]
Hey

`shield` or to be more precise the `s3` plugin behaves weirdly whenever the given `s3` bucket is not accessible or does not exist. Also the error is different on various `plugins`.

Example:

`mongo` plugin:

The `mongo` plugin simply never exists and the job is running until it is killed manually. There are no information in the logs which imply that the bucket is not reachable, does not exist or the user has not the required access permissions.

When turning on `debug` log, one can see this:

```
(...)

2017-04-05 10:28:55.567867398 +0000 UTC shield-agent: DEBUG: O:{

2017-04-05 10:28:55.567949432 +0000 UTC shield-agent: DEBUG: O:    "key": ""

2017-04-05 10:28:55.568119068 +0000 UTC shield-agent: DEBUG: O:}

2017-04-05 10:28:55.56819742 +0000 UTC shield-agent: DEBUG: E:DEBUG> 'store' action returned minio.ErrorResponse{XMLName:xml.Name{Space:"", Local:"Error"}, Code:"NoSuchBucket", Message:"", BucketName:"shield-dev", Key:"", RequestID:"tx000000000000000009bb6-0058e4c6e7-e746a-default", HostID:"e746a-default-default", AmzBucketRegion:""}

2017-04-05 10:28:55.568903624 +0000 UTC shield-agent: DEBUG: E:2017-04-05T10:28:55.568+0000     done dumping test.serviceInstanceBinding (5 documents)

2017-04-05 10:28:55.569156006 +0000 UTC shield-agent: DEBUG: E:

2017-04-05 10:28:55.570396706 +0000 UTC shield-agent: DEBUG: E:2017-04-05T10:28:55.570+0000     done dumping
(...)
```

The `mysql` plugin does this:

```
mysqldump: Got errno 32 on write
Unable to exec '/var/vcap/packages/shield-mysql/bin/mysqldump': exit status 5
TASK FAILED!!  shield worker 3 failed to execute the command against the remote agent <IP>:5444 (Process exited with: 4. Reason was:  ())

EXITING 4
TASK FAILED!! No restore key detected in worker 3. Cowardly refusing to create an archive record
```

which also does not really help. 

Would be great if `shield` simply does an `exit 1` with `Could not access bucket %s, bucketname`.

**Comment by jhunt** [comment]
shield-pipe is supposed to fail on SIGPIPE.  Is the s3 plugin not exiting when it can't connect to S3?

**Comment by jhunt** [comment]
It would appear that `mongodump` is the culprit here, as it seems to explicitly ignore the SIGPIPE that the s3 plugin is sending it upon failure.

Short of fixing mongotools, there is nothing we can do about this.

To verify, can you determine what happens if you pipe `mongodump` into any other command that exists earlier, like `mongodump | /root/secret` as a normal (non-root) user?

**Comment by janaurka** [comment]
i really don’t know if it is smart to put such a statement in public, but pretty much everything i’ve seen (and yes, I did some work, for example on this ... [mongo-boshrelease](lhttps://github.com/cloudfoundry-community/mongodb-bosh-release)) around `mongodb` simply makes me angry or at least feel quite bad.

oh and i’m really missing an appropriate emoji to tag your latest reply, the `not so amused` emoji is simply not enough.

@jhunt: good find. maybe it is worth to document this. I hope I’ll find some time tomorrow during work.

**Comment by jhunt** [comment]
Might be worth following up with the mongotools team as to why they ignore SIGPIPE?  Seems to me that if you are dumping data down a pipe for backup purposes, and the pipe bursts, you would want to know so you could avoid a blocking write bound for nowhere?

It would also probably be enlightening to see what's in the TOOLS-1366 ticket they referenced in that commit.

**Comment by janaurka** [comment]
@jhunt: I’ll try to find some time to do that tomorrow. But I’m not willing to invest some time during my freetime in a product which kinda frustrates me during work ;-)

But we (at $work) are using `mongodb` so I profesionally have an interest in stable backups.

I plan to do at least update this bug here and if there is some valid info or a working workaround I’ll try to either document or implement this properly.

**Comment by jhunt** [comment]
It's possible we could shim in something around `mongodump` that keeps the blocking write from hanging the entire process...  I'll do some investigation to see what's feasible there.

**Comment by jhunt** [comment]
Found their JIRA link (it was in the README); Gabriel Russell had this to say about explicitly ignoring SIGPIPE:

> You should at least manually test that dumping and exporting to a pipe don't hang when the reader goes away, with this patch.

So it might be worthwhile to bring this up on their Github page as an issue?

**Comment by janaurka** [comment]
I’ve created a ticket on their Jira instance regarding this: https://jira.mongodb.org/browse/TOOLS-1650

Let’s see what happens. When looking at the code this does not look like it’s a big thing to change.

If they do not change, maybe it would be the most straight forward solution to simply modify the code inside of https://github.com/mongodb/mongo-tools/blob/57233a4ef048b7f26bd5e4a6f8393160491c4306/common/signals/signals.go#L31 and properly document the change... Should be easy to simply add `SIGPIPE` to the list of signals the tool is listening to...
