### ISSUE TITLE
Retain minimum archives.

### ISSUE THREAD

**Issue by krutten** [starkandwayne/shield#27]
New value for retention policy to define a minimum number of archives to keep.  When scanning for archives to purge, we should count the most recent good archives and delay the purge if the minimum number is not met.

Use case:  Site that "hibernates" part of the year, backups may be turned off so new backups would not be created and after the retention period all archives would be purged meaning zero backups would exist.  With a minimum of "3" set for example, the last three would be retained until new backups started again.  This would allow the site's DB to be removed while hibernating and the last "good" archive to be restored when the site came out of hibernation.

Use case: Failing backups.  With short retention dates, if the backups fail repeatedly for a that length, all backups would be purged.  Failed backups should be resolved as quick as possible but when that is not possible, it would be beneficial to keep the last few "good" backups for emergencies.

**Comment by jhunt** [comment]
I'm still not convinced these are good reasons to complicate the core backup code.  Closing this, and if we have a real-world case (that wouldn't have been covered by valid monitoring), we can re-visit.
