### ISSUE TITLE
Allow "shield create backend" with --ca-cert

### ISSUE THREAD

**Issue by drnic** [starkandwayne/shield#278]
In https://github.com/starkandwayne/shield-boshrelease/tree/links-and-cloud-config it will be easy/default to deploy SHIELD with TLS and a self-signed certificate. 

It would be delicious for `shield create-backend` to support a `--ca-cert` flag to consume the root ca.

**Comment by thomasmmitchell** [comment]
@drnic I'm looking to potentially target this soon. Can you somehow recall what you were talking about several months ago and give more information / an example on expected usage?

**Comment by drnic** [comment]
@thomasmmitchell in our profession we would help everyone if we moved ppl away from `-k` or any variation of "skip ssl/tls validation" in our clients.

For example, https://github.com/cloudfoundry/bosh-cli provides `bosh --ca-cert path/to/cert alias-env` to cache the root CA for all future client interactions. `bosh2` no longer supports `-k` or any SSL validation skipping.

The CF CLI team is also starting to investigate adding support for specifying custom root CAs.

Can we move towards this too and eventually get rid of `-k`?

**Comment by thomasmmitchell** [comment]
I've never used `--ca-cert` on bosh2, but if I'm imagining a concept that solves this problem, I'm assuming that you give it that root CA to treat as trusted, such that your self-signed cert on the deployment is accepted, while someone else's garbage would shoot back with a TLS issue. That's a good idea, and I would definitely like that feature.

As for getting rid of `-k`... it's not happening _soon_. However, once `--ca-cert` is a thing, I'm fine with calling it deprecated... or possibly putting a quick "you should feel bad, use this other thing" line when folks use `-k` or a backend marked to skip TLS verification. I'm not married to the idea of the `-k` flag, even though I have to use it more often than I'd like. In the end, I'm not sure if I'll remove the flag entirely, so much as I might just stop advertising it. I'll have to see if a `-k`less workflow causes issues in any contexts. Either way, the final decision on its removal is one for another day... say... pending major version 9.

**Comment by jhunt** [comment]
This has been merged into v8

**Comment by drnic** [comment]
@thomasmmitchell how do you use `bosh2` without `bosh alias-env --ca-cert` or setting `$BOSH_CA_CERT`?

**Comment by drnic** [comment]
thanks for adding --ca-cert

**Comment by thomasmmitchell** [comment]
I either use it or have an environment where the cert is legitimate
