### ISSUE TITLE
CF/UAA OAuth backend not working properly

### ISSUE THREAD

**Issue by geofffranks** [starkandwayne/shield#285]
Membership verification is failing due to bad UAA filter requests. Not sure if the API changed, or if it was bad from the get-go, but we should be doing `displayName%20eq%20%22my-value%22` instead of displayName=%22my-value%22`.

Additionally there seems to be a bug with our session stores not saving properly to the database. Seeing two entries in the sessions table using the same `key` attribute, but different values. Instead of replacing, it's adding. Then when the user comes to authenticate, the initial one is being retrieved which is invalid, and the request fails. This is either a bug in our use of goth.Sessions, or a bug in goth.Sessions.

**Comment by jhunt** [comment]
This has been fixed in v8
