### ISSUE TITLE
Clickjacking vulnerability

### ISSUE THREAD

**Issue by cweibel** [starkandwayne/shield#288]
Can the HTTP header be modified with:
 - X-Frame-Options: DENY or SAMEORIGIN (if embedding)
 - Content-Security-Policy: frame-ancestors 'none' or 'self' (if embedding)

**Comment by thomasmmitchell** [comment]
@jhunt Is this a vulnerability, or just something to make sure isn't a vulnerability (I assume this was a concern that was brought up while pairing on the web ui)?

**Comment by jhunt** [comment]
This was found in an OWASP security review.  No research has been done on exactly _how_ one might take advantage of the vulnerability; it was a box on a check list.

**Comment by jhunt** [comment]
This may also be interesting to run through, if we set up a publicly accessible SHIELD:

https://observatory.mozilla.org/

**Comment by jhunt** [comment]
This is in v8 now.
