### ISSUE TITLE
Investigate Sub-Par BOSH backup/restore Scenario

### ISSUE THREAD

**Issue by jhunt** [starkandwayne/shield#294]
jovitha in CF Slack reported that the following steps were necessary to recover a BOSH:

> Steps to restore bosh
> We followed the below steps to achieve it:
> 1)  Prerequisites:
>       $ ssh to bosh vm using vcap user  ( ssh -i <path_to_private key> vcap@bosh_ip
> 2) next become the root user to execute commands of monit
> 3) Stop all connection to all database
>       $ monit stop all
> 4) Restart postgres and shield-agent 
>      $ monit start postgres
>      $ monit start shield-agent
> 5) shield restore archive(uuid)
> 6) next we need to move where psql binary is present
>      $  cd var/vcap/packages/postgres-9.4/bin 
> 7) We need to login into postgres database using vcap user
>      $ ./psql -d postgres -U vcap
> 8) next we need to change the roles of boshdb user 
>      $ ALTER ROLE boshdb CREATEROLE CREATEDB;
>      $ ALTER ROLE boshdb CREATEROLE LOGIN;
> 9) To quit the postgres database
>      $ \q
> 10) Restart all processes on bosh vm 
>      $ monit restart all

Stand up a BOSH director with something useful on it, and run through a backup/restore cycle with it, to see if the above steps are absolutely required, and if we can improve the experience with backing up and restore BOSH directors.

**Comment by ramonskie** [comment]
this can be solved now with the shield-bbr support
as of pcf 1.11

**Comment by jhunt** [comment]
FWIW, we've been backing up and restoring the BOSH director database without doing all of those steps (and without BBR) for years.
