### ISSUE TITLE
Bosh restore failing using shield, when bosh deployed with new IP

### ISSUE THREAD

**Issue by cfmagnum** [starkandwayne/shield#295]
Hello team,

I am testing a scenario to restore bosh using shield but the newly deployed bosh should have different IP.

I tried to restore bosh using shield and my restore was done to a certain extent but vms were missing of the service which previous bosh deployed.
I could obtain the restored bosh with old bosh director uuid,stemcells uploaded, releases uploaded and  the deployments of previous bosh.
New restored bosh tried to resurrect and create the vm but is unable to.
Old bosh deployed on ip eg. x.x.1.8
New(restored) bosh deployed on ip x.x.1.9
Attaching the screenshots for the same.
![bosh_restore_failed](https://user-images.githubusercontent.com/13657881/27473655-89ffe942-581d-11e7-9a87-6db1e40caa25.png)

Can some one help me on this?
Regards,
Jovitha

**Comment by szaouam** [comment]
Hi,

You may need to modify the backup file before restoring it.

Each deployment have a bosh_addr: https://ip_of_director:25555   attribute (the ip address of bosh director) . 
So if you want to restore into an other bosh deployment( with different ip address ) you need to replace the existing ip address into the backup file.

Best regards,

**Comment by cfmagnum** [comment]
Hi, 

I tried changing the bosh ip in backup file for restoring bosh using shield but it dint work for me.

Regards,
Jovitha

**Comment by norman-abramovitz** [comment]
Can you provide some details on what failed?

**Comment by cfmagnum** [comment]
When we restored bosh using the new ip ,restore failed.
![restore_failed_1](https://user-images.githubusercontent.com/13657881/27897371-8b86ce32-623d-11e7-9976-b3ce198d6430.PNG)
![restore_failed_2](https://user-images.githubusercontent.com/13657881/27897372-8b876e82-623d-11e7-8a13-6a8938bfc71d.PNG)

Please find the attached screenshots of the error.

**Comment by jhunt** [comment]
This looks like an attempt to restore a backup generated by a newer version of pgdump to an older version of postgres.

I don't know if you still need assistance with this (it's been quite some time...)
