### ISSUE TITLE
Timespec support for "every X hours [from X:XX]"

### ISSUE THREAD

**Issue by skburgart** [starkandwayne/shield#300]
Hey all,

Our use case requires backups every 4 hours, which the timespec does not support. For now we can create multiple schedules/jobs to match the hours that we need backups, but we'd like to be able to represent this case with a single schedule.

**Comment by karampok** [comment]
Hello, this seems a very useful feature, is it scheduled?

Currently we have the same issue because we want to have a backup every 6 hours.

Thanks!

**Comment by jhunt** [comment]
I can see about including it in the v8 milestone.

**Comment by jhunt** [comment]
This is in v8
