### ISSUE TITLE
Bad error msg if a plugin is missing

### ISSUE THREAD

**Issue by bodymindarts** [starkandwayne/shield#301]
I've spent some time investigating this output from a shield installation. It turned out the google plugin was missing due to an old release version. Point it we could use a better error message when the plugin is not found.
```
$ shield task 84a66610-f307-40b1-b9d8-ac74e26cee7e -k
UUID:       84a66610-f307-40b1-b9d8-ac74e26cee7e
Owner:      jcarter@
Type:       backup
Status:     failed

Started at: Tue, 11 Jul 2017 11:22:44 +0000
Stopped at: Tue, 11 Jul 2017 11:22:44 +0000

Job:        gcp-proto-bosh (72eb210a-45ba-422e-9160-4bb24b8363e9)

Log:        TASK FAILED!!  shield worker 4 failed to execute the command against the remote agent 10.0.1.32:5444 (ssh: command {"operation":"backup","target_plugin":"postgres","target_endpoint":"{\"pg_host\":\"10.0.1.2\",\"pg_password\":\"<password>\",\"pg_port\":\"5432\",\"pg_user\":\"vcap\"}","store_plugin":"google","store_endpoint":"{\"bucket\":\"backups\"}","restore_key":""} failed)
            WORKER FAILED!!  shield worker 4 failed to parse JSON response from remote agent 10.0.1.32:5444 (EOF)
```

**Comment by thomasmmitchell** [comment]
With the coming agent changes for v8, we should be able to determine whether or not an agent actually has the desired plugin. At that point, we should be able to keep you from making a target/store on a backend without the desired plugin in the first place.

**Comment by jhunt** [comment]
v8 agents now report that they could not find plugin 'x' in the plugin path (which is configurable on the agent)
