### ISSUE TITLE
CLI should take advantage of v2 API plugin form info

### ISSUE THREAD

**Issue by thomasmmitchell** [starkandwayne/shield#304]
Because writing JSON on the command line with no arrow key support or validity checking is inhumane.

This is a stretch goal for v7 and may need to be pushed until later into v7 support.

**Comment by thomasmmitchell** [comment]
This is still pending the completion of the agent API and the updating of the plugins

**Comment by jhunt** [comment]
Plugin Metadata is complete and implemented on the backend (Agent → Core).  We'll be shoring up the `/v2/` API this week and next to expose the information on a per-agent basis.

**Comment by thomasmmitchell** [comment]
As in the daemon can gather the info and expose it through the API?

**Comment by jhunt** [comment]
The code is currently gathering the information from the agents, and as of d306ec0, the agents are able to supply it to the core.  I don't believe we have an API for retrieving it for front-end uses yet.

**Comment by thomasmmitchell** [comment]
To get it off the agents, would you need the ssh key?

**Comment by jhunt** [comment]
No.  It's in the database, in core.  But there is no `/v2/...` API call to get it out of the database, so CLI can't use it (yet)

**Comment by jhunt** [comment]
Spin up `./bin/testdev`, wait about 2 minutes, and then issue the following SQL query: `SELECT * FROM agents` and you'll see what I mean.

**Comment by thomasmmitchell** [comment]
I'm assuming there's a polling interval that causes the 2 minute wait?

**Comment by jhunt** [comment]
Yeah.  The agents register something akin to a "ping me!", and the core only checks on the agents every X minutes, to keep spam down.

**Comment by jhunt** [comment]
Buckler CLI supports v2 API natively.
