### ISSUE TITLE
GetJobsStatus API function with MySQL

### ISSUE THREAD

**Issue by karampok** [starkandwayne/shield#308]
Hello there, 
we have started seeing in web gui that all jobs are in 
```
Last Run | Status
NEVER | PENDING
```

By examining the code,  it looks like that this [part](https://github.com/starkandwayne/shield/blob/master/db/jobs.go#L97:L138)
is not working in MySQL as it should work in Postgres.

Especially this line
https://github.com/starkandwayne/shield/blob/master/db/jobs.go#L128

Have you seen this issue? 

Thank you in advance

**Comment by karampok** [comment]
Hi again, could you let me know if this is a valid issue in your opinion?

Thanks!

**Comment by norman-abramovitz** [comment]
Looks like a valid issue.

**Comment by jhunt** [comment]
This will be taken care of in v8, when we switch to an internal data store.

**Comment by karampok** [comment]
Cool, thx
