### ISSUE TITLE
make restore-deps fails making it impossible to build from source

### ISSUE THREAD

**Issue by bodymindarts** [starkandwayne/shield#316]
```
 make restore-deps
godep restore ./...
godep: error downloading dep (git.openstack.org/openstack/golang-client/objectstorage/v1): unrecognized import path "git.openstack.org/openstack/golang-client/objectstorage/v1"
godep: error downloading dep (git.openstack.org/openstack/golang-client/openstack): unrecognized import path "git.openstack.org/openstack/golang-client/openstack"
godep: error downloading dep (git.openstack.org/openstack/golang-client/util): unrecognized import path "git.openstack.org/openstack/golang-client/util"
godep: Error downloading some deps. Aborting restore and check.
make: *** [restore-deps] Error 1
```

**Comment by thomasmmitchell** [comment]
You don't need to restore deps when building locally - packages in the vendor directory should override versions in your GOPATH.

**Comment by thomasmmitchell** [comment]
restore-deps should only be necessary for that if you're working on the project when it isn't nested in your GOPATH at the proper path... which I wouldn't recommend because that'll lead to other pathing issues that you wouldn't like.

**Comment by bodymindarts** [comment]
Got it it just works without that. Should perhaps remove from makefile then.

**Comment by thomasmmitchell** [comment]
Yup, I agree. It was from when GOVENDOREXPERIMENT15 was still a thing and Godeps workspaces were a thing and blah blah blah. Obsolete now. Run godep restore if you REALLY need it
