### ISSUE TITLE
Incorrect "skip_ssl_validation" conversion in s3 plugin

### ISSUE THREAD

**Issue by jraverdy-orange** [starkandwayne/shield#375]
Hi,

When I check the "Skip SSL Validation" checkbox in the "Edit storage System" screen, then the storage plugin is configured with a `"skip_ssl_validation": "on"` property.

When I use ` buckler`, I can get this property set to `"skip_ssl_validation": "true"`.

But in both cases the storage plugin is not expecting a string but a boolean value.

Here are the error produced in `shieldd.log`:
```
✗ skip_ssl_validation  'skip_ssl_validation' key in endpoint json is not of type 'boolean'
s3: invalid configuration
EXITING 4
task failed!
```
Could you get it fixed?
Thanks!

**Comment by jhunt** [comment]
Sure, I can get this fixed.
