### ISSUE TITLE
Shield deployment deleted.

### ISSUE THREAD

**Issue by cfmagnum** [starkandwayne/shield#376]
Hi team,

If accidentally shield deployment is deleted .Is there any way to restore from previous backups because shield archives are not visible after new deployment. 

Thanks in advance
Aishwarya Wani

**Comment by jhunt** [comment]
What version of SHIELD?

Prior to (the still beta) v8, if you have access to the cloud storage out-of-band, you can just download the backup archives and manually restore them to the SHIELD VM.

**Comment by Jyoti1Barthwal** [comment]
Currently we are using v6, but if we hit a shield upgrade to v8  , recovery.* properties have been removed. So what steps do we need to perform for recovering shield in v8?

**Comment by jhunt** [comment]
For now, stick with v6; The next rev of v8 will be getting a UI upgrade to take over the `recovery.*` duties from the manifest.
