### ISSUE TITLE
buckler --version returns buckler v¯\_(ツ)_/¯

### ISSUE THREAD

**Issue by rkoster** [starkandwayne/shield#386]
`buckler --version` returns `buckler v¯\_(ツ)_/¯`, would like to have a proper version to check with bucc so we can update the cli when needed.

**Comment by jhunt** [comment]
Yes it does.

**Comment by rkoster** [comment]
:trollface: I noticed.. is there a particular reason for this or just not yet implemented?

**Comment by jhunt** [comment]
It's on master now.

**Comment by rkoster** [comment]
Thanks!
