### ISSUE TITLE
v8: Creating a Job from the WebUI, the name will be `a random Name?`

### ISSUE THREAD

**Issue by janaurka** [starkandwayne/shield#387]
When creating a job through the WebUI, the Name of the Job when queries using the `shield-cli/buckler` the name is: `a random name?`

A full detailed query:

```
$ shield --tenant test job <id/name>
UUID:          <id>
Name:           a random name?
Status:

Schedule:       daily at 3:00
Policy:         30d
Expires in:     30 days

Data System:    Concourse PROD DB
Backup Plugin:  postgres
SHIELD Agent:

Cloud Storage:  default-s3
Storage Plugin: s3

Fixed-Key:      false
Notes:
```
It’s easily editable using the following command:

```
$ shield update-job -t test-n "Concourse PROD DB Daily Backup" <id/name>
UUID:    8bad287d-6a81-41ca-8c48-5f0c07c86b95
Name:    Concourse PROD DB Daily Backup
Summary:
```

The `name` from the WebUI seems to get lost...

**Comment by jhunt** [comment]
Ha!  I went to all the trouble to build out the automatic naming during the Web UI wizard, only to throw away the name at the most crucial moment.  Classic me.

I'll get this fixed this morning, and maybe get it out before the next release.

@daviddob ^^

**Comment by wayneeseguin** [comment]
At least we now have confirmation that @jhunt and @daviddob are the same person 😂

**Comment by janaurka** [comment]
Oh, this seems still to be a problem, it’s not `a random name?` anymore, but it’s will take the default name which the WebUI offers. If it’s an `hourly` schedule, the jobs will be called `Hourly` even if there was another name inserted.
