### ISSUE TITLE
Jobs are not pausable / --paused flag not recognized in update-job

### ISSUE THREAD

**Issue by janaurka** [starkandwayne/shield#390]
Hey,

I’m running:
* Shield 8.0.6
* Deployed through the `bosh-release`
* on vSphere 5.5/6.0

When trying to update a `job` the flag `--paused` is not being recognized. So I cannot `unpause` or `pause` a job.

```
shield -t test update-job --paused 8bad287d-6a81-41ca-8c48-5f0c07c86b95
!!! unrecognized flag `--paused``
```

Expected result: I can pause/unpause any job and any given time.

**Comment by jhunt** [comment]
Have you tried `shield -t test pause-job 8bad287d-6a81-41ca-8c48-5f0c07c86b95`?

**Comment by janaurka** [comment]
Huh, that works. 

Then there are two things:

1. in `update-job` the `--paused` flag is mentioned (i’ll try to create a PR to fix that).
2. if a job is paused i see no reference in the WebUI, not in the general view, nor in the dedicated job view (will create a new bug for this one).

:)
