### ISSUE TITLE
Support for AWS Instance Profiles in the s3 plugin

### ISSUE THREAD

**Issue by geofffranks** [starkandwayne/shield#402]
Would it be possible to add support for authenticating to S3 using EC2 instance profiles as an alternative to using  `access_key_id` and `secret_access_key` for the `s3` plugin?

**Comment by jhunt** [comment]
Sure.  Can you point me to docs on how that works from the ground level?

**Comment by geofffranks** [comment]
Instance profiles overview: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html

Retrieving the creds from the env: https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-ec2_instance-profiles.html

Using the retrieved creds: https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_use-resources.html

Mentioned this + some possible concerns in shield slack, will summarize the outcome of that discussion here

**Comment by jhunt** [comment]
Merged in #423
