### ISSUE TITLE
question about "No 'bbr_deployment' key specified in the endpoint json"

### ISSUE THREAD

**Issue by eujungkim** [starkandwayne/shield#409]
I tried to backup my cf deployment using BOSH BBR Deployment Plugin and met below error logs.

bbr plugin starting up...
 bbr_deployment   No 'bbr_deployment' key specified in the endpoint json
 
It seems that bosh director endpoint must return "cf" using json response.
But I think the normal bosh director does not return it.

What should I do to fix this error?

**Comment by jhunt** [comment]
The `endpoint json` it's referring to is the configuration for the backup target.  The `bbr_deployment` plugin needs to know which deployment you want BBR to backup, which you would give via the Web UI when you configured the job.

**Comment by eujungkim** [comment]
How can I set 'bbr_deployment' to bbr-director plugin?
There is no field about it in Web UI.

**Comment by jhunt** [comment]
Seems like a bug in the BBR plugin.  @ramonskie care to take a look?

**Comment by ramonskie** [comment]
i will take a look it at today.

**Comment by ramonskie** [comment]
the deployment field was not there since the rewrite

**Comment by eujungkim** [comment]
@ramonskie I installed shield using shield-boshrelease v8.0.8. 
And I do not use shield-addon-bbr-boshrelease. I don't know the existence of that before. Should I use it to backup bosh director and bosh deployment(cf)?
And I'm trying to backup both the bosh director and a bosh deployment(cf).

**Comment by ramonskie** [comment]
okay well the `bbr_plugin` needs https://github.com/shieldproject/shield-addon-bbr-boshrelease
alongside the agent you use from shield.
otherwise it can't find the bbr cli.
