### ISSUE TITLE
Restoring using purged archive is not blocked.

### ISSUE THREAD

**Issue by eujungkim** [starkandwayne/shield#411]
I'm using shield v8.0.8 and it is installed by shield-boshrelease.

I purged an archive like below.
```
$ ./shield archives
UUID                                  Key                                                                 Status
====                                  ===                                                                 ======
e430f91b-f26f-47c4-871c-be823e6f2451  /2018/05/16/2018-05-16-125302-b42fa761-1a0d-4fc8-8e26-91c0b19d314f  expired
```
When I checked my S3 store after purging, the backup file related above archive was not deleted. Is it your design concept?

And after then, in web UI and cli, restoring using the purged archive is not blocked. In web UI, "Go >>" button of the archive was enable still.

When I execute this command, shield start to download backup file from my S3.
```
$ ./shield restore-archive e430f91b-f26f-47c4-871c-be823e6f2451
```

**Comment by eujungkim** [comment]
Oh! It takes a few minute to purge archive.
After 10~20 minute, status of the archive is changed to "purged".
And the backup file in s3 storage is deleted and try to restore using the purged archive is failed.
```
$ ./shield archives
UUID                                  Key                                                                 Status
====                                  ===                                                                 ======
e430f91b-f26f-47c4-871c-be823e6f2451  /2018/05/16/2018-05-16-125302-b42fa761-1a0d-4fc8-8e26-91c0b19d314f  purged
shield/4b0a34c1-d0c7-45b3-886f-eabba68cb7cf:/var/vcap/packages/shield/bin$ ./shield restore e430f91b-f26f-47c4-871c-be823e6f2451
```
Purging archive works well. But I wonder why the restoring using "expired" archive is possible.
Anyway the problem is solved, so I close this issue.

**Comment by jhunt** [comment]
"expired" just means "its beyond retention window".  As you found out, there is a background path (the so-called "slow loop") that purges expired archives.

In most cases, with properly configured retention policies, the most recent archive will _not_ be expired, and that's usually the one you want.
