### ISSUE TITLE
"Make All" not working

### ISSUE THREAD

**Issue by SalamatKhan** [starkandwayne/shield#412]
When running "make all" after cloning the repo, I am getting following errors due to an underscore "_" being added to all the paths:

$ make all
go list ./... | grep -v vendor | xargs go fmt
can't load package: package _/Users/<userid>/ops/shield/agent: cannot find package "_/Users/<userid>/ops/shield/agent" in any of:
	/usr/local/go/src/_/Users/<userid>/ops/shield/agent (from $GOROOT)
	/usr/local/go/bin/src/_/Users/<userid>/ops/shield/agent (from $GOPATH)
can't load package: package _/Users/<userid>/ops/shield/client/v2/shield: cannot find package "_/Users/<userid>/ops/shield/client/v2/shield" in any of:
	/usr/local/go/src/_/Users/<userid>/ops/shield/client/v2/shield (from $GOROOT)
	/usr/local/go/bin/src/_/Users/<userid>/ops/shield/client/v2/shield (from $GOPATH)
can't load package: package _/Users/<userid>/ops/shield/cmd/shield: cannot find package "_/Users/<userid>/ops/shield/cmd/shield" in any of:
	/usr/local/go/src/_/Users/<userid>/ops/shield/cmd/shield (from $GOROOT)
	/usr/local/go/bin/src/_/Users/<userid>/ops/shield/cmd/shield (from $GOPATH).....
.....
The GOPATH and GOROOT are set as follows:
GOPATH="/usr/local/go/bin"
GOROOT="/usr/local/go"

Results of go version:
$ go version
go version go1.10.2 darwin/amd64

**Comment by jhunt** [comment]
Where is the code checked out to?

**Comment by SalamatKhan** [comment]
The path where the repo was cloned on the macbook is /Users/<userid>/ops.

**Comment by jhunt** [comment]
Try moving that working copy to `$GOPATH/src/github.com/starkandwayne/shield` and trying the `make all` again from there.

**Comment by SalamatKhan** [comment]
Yes, this worked great. Thank you!

**Comment by jhunt** [comment]
🎉
