### ISSUE TITLE
Bosh Director Cert. Error

### ISSUE THREAD

**Issue by Mohsin-Ahmed** [starkandwayne/shield#414]
I am getting the following error when trying to run a backup for bbr-deployment. Have formatted the cert. /PEM file using `sed ':a;N;$!ba;s/\n/\\n/g' ca.pem` to create one." Have tried removing the double \\n with a single \n as well, however get the same error. The initial validation passes for all the fields including storage. We are using Shield v 8.0.8.

```` Running backup task (using bzip2 compression)
=============================================
bbr plugin starting up...
1 error occurred:
error 1:
error building bosh director client: Validating Director connection config: Parsing certificate 1: Missing PEM block


exit status 1
Access Denied (AccessDenied) [raw 
AccessDenied
Access Denied136a7509:1636082614e:28c9c:2d8]

EXITING 4
shield worker 1 unable to run command against 10.xx.xx.xx:5444
````

**Comment by Mohsin-Ahmed** [comment]
Here are some additional details:
Using Shield    8.0.8 and 
Shield-addon-bbr  0.1.1
We deployed the Shield in Global and trying to back up a cf-deployment (PAS 2.0.9) with bbr-deployment by targeting one of the sandbox bosh director.
````
UUID                                  Name               Summary  Plugin          SHIELD Agent       Configuration
====                                  ====               =======  ======          ============       =============
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  pcf-sandbox           bbr-deployment  10.xx.xxx.xx:5444  {
                                                                                                      "bbr_bindir": "/var/vcap/data/packages/bbr/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/bin <path of bbr on the Shield server>",
                                                                                                      "bbr_cacert": "----BEGIN CERTIFICATE-----\n<ca-cert of bosh director in sandbox>\n-----END CERTIFICATE-----",
                                                                                                      "bbr_deployment": "cf-xxxxxxxxxxxxxxxxx",
                                                                                                      "bbr_password": "<vcap password>",
                                                                                                      "bbr_target": "<Private IP for bosh dir. for sandbox",
                                                                                                      "bbr_username": "vcap"
                                                                                                     }
````

**Comment by jhunt** [comment]
The documentation for the `bbr-deployment` plugin explain that the PEM-formatted X.509 certificate should have all newlines removed and replaced with single space characters (ASCII 0x20).  If that works for you, then I'll see if we can't amend the BBR plugins to be a little nicer to operators and replace all runs of whitespace appropriately.

**Comment by Mohsin-Ahmed** [comment]
I formatted the .pem certificate using "sed ':a;N;$!ba;s/\n/\\n/g' ca.pem` to create one." as mentioned in the Help which adds \n for every new line. To confirm - I need to replace all the \n with a single space?

**Comment by jhunt** [comment]
Give that a try.  I know the documentation says to escape the newlines, but I didn't see anything in the code that was unescaping them.

**Comment by jhunt** [comment]
@Mohsin-Ahmed any luck?
