### ISSUE TITLE
Large backups with xtrabackup fail regularly

### ISSUE THREAD

**Issue by ampersand8** [starkandwayne/shield#417]
**Goal**
Backup Galera-Cluster with > 300 GB data with the xtrabackup plugin.

**Problem**
For large backups I'm experiencing a lot of failures (60% of backups fail). After some tests I think it might be **due to the slow bzip**, which in my case takes about 4 hours. When splitting up the backup process in shield-pipe to write first to a temporary file (bzipped) and then streaming this file to s3 or simply remove the bzip step, the backup is always successful.

**Error Message**
```
Put https://<S3-ADDRESS>/2018/06/11/2018-06-11-030001-fc6ff210-0d69-4855-ba78-294019379daf?partNumber=1&uploadId=4a2cde266f5f451fa302bb2182c0886e: net/http: HTTP/1.x transport connection broken: write tcp <CLIENTIP>:57248-><S3IP>:443: write: connection reset by peer
✗ Creating archive failed
Unable to exec 'tar': signal: broken pipe

TASK FAILED!!  shield worker 49 failed to execute the command against the remote agent <CLIENTIP>:5444 (Process exited with: 4. Reason was:  ())
EXITING 4
TASK FAILED!! No restore key detected in worker 49. Cowardly refusing to create an archive record
```

**Proposal**
It'd be great to have some more control over the whole shield-pipe process, also with options for all plugins like xtrabackup which provides a compress option. This additional config could be added in the SHIELD_TARGET_ENDPOINT. Also, with the additional flexibilty edge cases could be more easily covered.

**Comment by jhunt** [comment]
For science, have you tried replacing the `bzip2` invocation in `shield-pipe` with `cat`?  I wonder how much of it is "bzip2 is slow" and how much is the interplay between two network pipes.

**Comment by jhunt** [comment]
In any event, the issue you're looking for is #373

**Comment by ampersand8** [comment]
When I replace `bzip2` with `cat` the whole backup takes about 1.5 hours (including s3 upload). I also tested just bzip2 alone with a 278 GB backup tar (`cat test.tar | bzip2 > /dev/null`), which took almost 4 hours.

Yes, being able to drop bzip2 as described in #373 would probably solve my problem. :+1: 

Additionally it'd be great if all plugins by default came with a custom options config for different operations. In my case I'd add the xtrabackup `--compress --compress-threads=8` option for backup and respectively `--decompress` for restore. That way it's no longer necessary to open a PR for use case specific things. I'd imagine a target config like this:
```
{
  "mysql_datadir": "/var/vcap/store/mysql",
  "mysql_password": "supersecretpassword",
  "mysql_socket": "/var/vcap/sys/run/mysql/mysqld.sock",
  "mysql_temp_targetdir": "/var/vcap/store/xtrabackups",
  "mysql_user": "backup",
  "mysql_xtrabackup": "/var/vcap/packages/xtrabackup/bin/xtrabackup",
  "custom_backup_options": "--compress --compress-threads=8",
  "custom_restore_options": "--decompress"
}
```
What do you think?

**Comment by jhunt** [comment]
I think I'm looking forward to reviewing those pull requests 😉

**Comment by jhunt** [comment]
optional compression is on the backlog, on deck after the next round of bug squashing:
https://trello.com/c/qRuHfBKu/71-make-compression-optional

**Comment by jhunt** [comment]
Compression is optional as of c0f60c8e, which should get cut into a release on Friday (AWS willing)

**Comment by jhunt** [comment]
(merged in #437)

**Comment by jhunt** [comment]
This should be resolved in 8.0.14, please have a look and see if it works for you 😄 

SHIELD: (v8.0.14): https://github.com/starkandwayne/shield/releases/tag/v8.0.14
BOSH release (v8.0.14): https://github.com/starkandwayne/shield-boshrelease/releases/tag/v8.0.14
Genesis Kit (v0.3.4): https://github.com/genesis-community/shield-genesis-kit/releases/tag/v0.3.4

**Comment by ampersand8** [comment]
Thanks a lot, that works for us. :+1:

With further tests we found that for us the best solution is compressing the backup with pbzip2 which allows us to substantially speedup the compression. With that backups also work consistently, and do not strain our storage that much.

**Comment by jhunt** [comment]
Interesting.  The new compression layer allows us to slot in entirely new compression schemes in future releases, without affecting backwards compatibility.  I would love to review a PR to add in pbzip2 (and perhaps an addon BOSH release to colocate it?)
