### ISSUE TITLE
Logo contribution

### ISSUE THREAD

**Issue by reallinfo** [starkandwayne/shield#442]
Hello, 

I am a graphic designer. I wanted to design a logo for shield. I used icons representing shield, backup and restore features. If you want it, i will send a pr. What do you think? I will wait for feedback. 

Best regards.

![shield](https://user-images.githubusercontent.com/36298335/43712654-9018c7aa-997f-11e8-9c40-a89dfe6bbae8.jpg)

**Comment by jhunt** [comment]
I appreciate the effort you put into this log; it looks fantastic!

Unfortunately, we already have branding guidelines, color palette selections and iconography / logowork.
