### ISSUE TITLE
Post-upgrade: v8 agent can't restore v7 backups

### ISSUE THREAD

**Issue by red-trela** [starkandwayne/shield#447]
Backups taken with a v7 agent can't be restored post-upgrade by a v8 agent as the v8 agent will try (and fail) to decrypt the non-encrypted v7 backup. Maybe the metadata can be used to decided whether the archive needs to be decrypted or not, or maybe the v8 agent should fallback to restoring without decryption if decryption fails.

**Comment by jhunt** [comment]
Is this the same issue that @Nbari reported in SHIELD slack?

**Comment by red-trela** [comment]
Yes, indeed

**Comment by nbari** [comment]
As a workaround https://github.com/starkandwayne/shield/pull/448

**Comment by jhunt** [comment]
Normally, we advise people to take a new backup once they upgraded an agent from v7 to v8.
