### ISSUE TITLE
editing stores in web ui do not set the previous state of checkboxes

### ISSUE THREAD

**Issue by thomasmitchell** [starkandwayne/shield#453]
.e.g if skip ssl validation was set and you edit in the web UI, the skip ssl validation checkbox is not set already.

**Comment by jhunt** [comment]
This should be fixed in the 8.1.0 release, which should be out the door by next week (just in time for CF Summit Philly!)

**Comment by jhunt** [comment]
Fixed in v8.1.0 (https://github.com/starkandwayne/shield/releases/tag/v8.1.0)
