### ISSUE TITLE
Consider updating golang crypto

### ISSUE THREAD

**Issue by dmolik** [starkandwayne/shield#457]
On newer versions of openssh, private keys are formatted using an "OPENSSH" style, which is incompatible with the version of golang crypto in /vendor, but newer versions of crypto support the openssh format.

**Comment by jhunt** [comment]
Have you tried updating the vendor deps?

**Comment by patrick1378** [comment]
We can't do this right now as we have issues with the agent completing the handshake with core with the update. We are however looking at alternate communication and control fabrics for the re-write.
