### ISSUE TITLE
Docker compose example doesn't work

### ISSUE THREAD

**Issue by Steve-Hand** [starkandwayne/shield#462]
With v8.0.16, the "build" script, part of the "Docker" steps, fails with the following error

cp: shield-agent: No such file or directory
cp: shield: No such file or directory

**Comment by Steve-Hand** [comment]
First, running "./demo/build" from the "shield" repo is not what the instructions say for "Docker" . 

But that operation also fails from OSX 10.13. with the same error. 

The "cd" operation at line 3 of "./demo/build", CDs to the repo root. Line 3 is "cd $(cd $(dirname ${BASH_SOURCE[0]})/.. && pwd)", which means CD to the parent of "demo" where the "build" file lives.

I think you may be wanting to CD to the directory the "build" script itself is in, presumably in order to run the script from any directory. 

There is neither a "shield-agent" nor a "shield" directory, i.e. "shield/shield-agent" or "shield/shield" directory, at the repo root, but these directories exist in the "shield/demo" directory.

**Comment by jhunt** [comment]
Ah well.  We're going to be building removing the demo altogether in the next release.

**Comment by jhunt** [comment]
This should be fixed in the 8.1.0 release, which should be out the door by next week (just in time for CF Summit Philly!)

**Comment by jhunt** [comment]
We have a new Docker Compose recipe (powered by new images that are now on docker.io).  Just ran through it on master and it works.  If you're still having issues getting SHIELD under Docker / Compose to work, please open a new ticket.
