### ISSUE TITLE
S3 plugin appears to be broken with Swiftstack S3 server using auth v2

### ISSUE THREAD

**Issue by Steve-Hand** [starkandwayne/shield#464]
When attempting to run an ad hoc backup using verified S3 configuration (auth URI and credentials) and AWS Signature Version 2, the following error is returned:

AWS authentication requires a valid Date or x-amz-date header (AccessDenied) [raw 
AccessDenied
AWS authentication requires a valid Date or x-amz-date headertx13292aa2b2c84f16b8dde-005bc8920d]

**Comment by jhunt** [comment]
Can you provide the S3 plugin configuration you are using, and details about the S3 work-alike you are using?

**Comment by Steve-Hand** [comment]
First, I’m not entirely comfortable with sharing the configuration details. Suffice it to say, these same configuration strings work with s3cmd and minio mc CLI and with the SHIELD v6.9.0. 

On the second question,  please see https://www.swiftstack.com/docs/admin/middleware/s3_middleware.html

**Comment by jhunt** [comment]
You can (and should) sanitize any identifying details

**Comment by Steve-Hand** [comment]
The config is
SHIELD Agent: 10.82.33.26:5444
Use Instance Profile: no
Access Key ID:<redacted>
Secret Access Key REDACTED
Bucket Name  <redacted> 
Path Prefix <redacted>
S3 Host <redacted>
S3 Port
AWS Signature Version 2
Multipart Upload Part Size 100M
SOCKS5 Proxy
Skip SSL Validation  no

**Comment by jhunt** [comment]
I suspect that the region fix for #465 (PR #467) will take care of this as well, since you will be able to use sig version 4.
