### ISSUE TITLE
S3 plugin appears to be broken with Swiftstack S3 server using auth v4

### ISSUE THREAD

**Issue by Steve-Hand** [starkandwayne/shield#465]
When attempting to run an ad hoc backup using verified S3 configuration (auth URI and credentials) and AWS Signature Version 4, the following error is returned:

The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'US' (AuthorizationHeaderMalformed) [raw 
AuthorizationHeaderMalformed
The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'US'txaacbdb1d22ae48bb9f403-005bc8a71aUS]

**Comment by Steve-Hand** [comment]
I’m not entirely comfortable with sharing the configuration details. Suffice it to say, these same configuration strings work with s3cmd and minio mc CLIs, and with the SHIELD v6.9.0.

On the second question, please see https://www.swiftstack.com/docs/admin/middleware/s3_middleware.html

**Comment by jhunt** [comment]
You can (and should) sanitize any identifying details

**Comment by Steve-Hand** [comment]
The config is
SHIELD Agent: 10.82.33.26:5444
Use Instance Profile: no
Access Key ID:<redacted>
Secret Access Key REDACTED
Bucket Name  <redacted> 
Path Prefix <redacted>
S3 Host <redacted>
S3 Port
AWS Signature Version 4
Multipart Upload Part Size 100M
SOCKS5 Proxy
Skip SSL Validation  no
