### ISSUE TITLE
Shield failed to restore to a different target for cf-db

### ISSUE THREAD

**Issue by xiujiao** [starkandwayne/shield#469]
Old CF db is backed up to webdav, with an archive id  `7efc03e6-4970-4982-bec2-f5a08ff1f04a`. Deployed new CF, trying to restore the archive from the old cf to the new cf using the same shield.
`NEW-cf-db` is the target name for new cf dbs.
Running the following command:
`shield -T restore-archive 7efc03e6-4970-4982-bec2-f5a08ff1f04a --to NEW-cf-db`
The new target is passed to the API call,but got an 404 error.
```
Request:
POST /v2/tenants/18c88c3c-7841-4761-babf-8ceb34d7b78b/archives/7efc03e6-4970-4982-bec2-f5a08ff1f04a/restore HTTP/1.1
Host: 10.131.160.6
Accept: application/json
Content-Type: application/json
X-Shield-Session: b0f723eb-0a2e-4812-9cae-1cf4cff23c75
{"target":"baedc663-337d-4beb-adeb-2f82c8e7876a"}
---------------------------
Response:
HTTP/1.1 404 Not Found
Connection: close
Content-Length: 151
Content-Type: application/json
Date: Fri, 19 Oct 2018 14:56:13 GMT
Server: nginx
{"error":"SHIELD API endpoint `GET /v2/tenants/18c88c3c-7841-4761-babf-8ceb34d7b78b/archives/7efc03e6-4970-4982-bec2-f5a08ff1f04a/restore' not found"}
```

**Comment by jhunt** [comment]
That shouldn't be a GET, it should be a POST.

I highly suspect this is an outdated CLI problem.  This was fixed in commit 7699af089, which was first available in [8.0.14](/starkandwayne/shield/releases/tag/v8.0.14) of the CLI:

> When restoring archives with the CLI, and targeting a different data
> system than the archive originally came from, everything (now) works
> as expected.

**Comment by xiujiao** [comment]
I thought we upgraded to latest cli, maybe we did for safe not shield. Will
check it Monday

**Comment by jhunt** [comment]
Any update?

**Comment by xiujiao** [comment]
I think they decided to move on without restore. So I never got a chance to
test it again
