### ISSUE TITLE
Agent test failing

### ISSUE THREAD

**Issue by jiangytcn** [starkandwayne/shield#475]
$ go version                                                                                                                                                /home/jiangytcn 
go version go1.10.3 linux/amd64

~/go/src/github.com/starkandwayne/shield dvlp.yacloud.io on  master ⌚ 15:25:47
$ make all                                                                                                                                                  
go list ./... | grep -v vendor | xargs go fmt
plugin/webdav/plugin.go
go build ./cmd/shieldd
go build ./cmd/shield-agent
go build ./cmd/shield-schema
go build ./cmd/shield-crypt
go build ./cmd/shield-report
go build ./cmd/shield
go build ./cmd/shield-migrate
go build ./plugin/dummy
for plugin in $(cat plugins); do \
	go build ./plugin/$plugin; \
done
export PATH=$PATH:test/bin; go list ./... | grep -v vendor | xargs go test
Running Suite: Agent Test Suite

Random Seed: 1546068358
Will run 41 of 41 specs

• Failure [0.047 seconds]
Agent
/home/jiangytcn/go/src/github.com/starkandwayne/shield/agent/agent_test.go:14
  Command Runner
  /home/jiangytcn/go/src/github.com/starkandwayne/shield/agent/agent_test.go:264
    collects output from the command pipeline [It]
    /home/jiangytcn/go/src/github.com/starkandwayne/shield/agent/agent_test.go:352

    Expected
        <string>: {
          "compression": "bzip2",
          "key": "9ea61fef3024caadf35dd65d466a41fb51a3c152"
        }
        
    to match JSON of
        <string>: {
          "key": "9ea61fef3024caadf35dd65d466a41fb51a3c152"
        }

    /home/jiangytcn/go/src/github.com/starkandwayne/shield/agent/agent_test.go:363

• Failure [0.279 seconds]
Agent
/home/jiangytcn/go/src/github.com/starkandwayne/shield/agent/agent_test.go:14
  Command Runner
  /home/jiangytcn/go/src/github.com/starkandwayne/shield/agent/agent_test.go:264
    handles backup operations with large output [It]
    /home/jiangytcn/go/src/github.com/starkandwayne/shield/agent/agent_test.go:375

    Expected
        <string>: {
          "compression": "bzip2",
          "key": "acfd124b56584c471d7e03572fe62222ee4862e9"
        }
        
    to match JSON of
        <string>: {
          "key": "acfd124b56584c471d7e03572fe62222ee4862e9"
        }

    /home/jiangytcn/go/src/github.com/starkandwayne/shield/agent/agent_test.go:390

•••

S [SKIPPING] [0.009 seconds]
Agent
/home/jiangytcn/go/src/github.com/starkandwayne/shield/agent/agent_test.go:14
  Command Runner
  /home/jiangytcn/go/src/github.com/starkandwayne/shield/agent/agent_test.go:264
    handles non-existent plugin commands for just target [It]
    /home/jiangytcn/go/src/github.com/starkandwayne/shield/agent/agent_test.go:462

    bin/shield-pipe/Run() needs some more work to suppress output in case of failure?

    /home/jiangytcn/go/src/github.com/starkandwayne/shield/agent/agent_test.go:475

**Comment by jiangytcn** [comment]
the issue happened after install shield* to go bin path
`go get -u github.com/starkandwayne/shield/...`
and then run make go-tests would lead to the failure

**Comment by jhunt** [comment]
PR Merged!  Thanks again.
