### ISSUE TITLE
Task listing includes username and password of MongoDB target

### ISSUE THREAD

**Issue by SteveH-US** [starkandwayne/shield#485]
The listing of the task for backing up a MongoDB DBMS includes UN & PW surrounded by "redacted" tag, but the UN & PW are still visible.

**Comment by SteveH-US** [comment]
And the store UN & PW are visible as well.

**Comment by jhunt** [comment]
What account are you using?

**Comment by SteveH-US** [comment]
The account used was assigned the "manager" system role and the "operator" role in the tenant.

**Comment by jhunt** [comment]
This should be fixed in the 8.1.0 release, which should be out the door by next week (just in time for CF Summit Philly!)
