### ISSUE TITLE
Backup run through UI does not show up as successful backup

### ISSUE THREAD

**Issue by SteveH-US** [starkandwayne/shield#486]
Using an account that has a system role of "engineer" and a tenant role of "operator", 
I ran existing backup job successfully.  I can see the successful run from the CLI, using the administrator user.  But the UI states, "This data system has never been backed up successfully." to the "operator"

**Comment by SteveH-US** [comment]
This issue appears to be related to the right of the user that ran the backup.

**Comment by jhunt** [comment]
As with #491, I believe this is a disconnect between the Restore wizard and the system detail page.  Will try to reproduce the full gamut of such dissonance in our 8.0 and 8.1 lab instances.
