### ISSUE TITLE
"full task log" appears only briefly on click

### ISSUE THREAD

**Issue by SteveH-US** [starkandwayne/shield#488]
While a backup is running, using Chrome " 71.0.3578.98", clicking on "full task log" for a "Scheduled Backup" results in the log only being displayed for a second or so before disappearing.

**Comment by jhunt** [comment]
This should be fixed in the 8.1.0 release, which should be out the door by next week (just in time for CF Summit Philly!)

**Comment by jhunt** [comment]
This has been verified in several production deployments of SHIELD.
