### ISSUE TITLE
Error streaming backup from remote instance. Error

### ISSUE THREAD

**Issue by Klojo** [starkandwayne/shield#489]
Hello, we have this problem with the BBR-Director Backup

Bosh deployed SHIELD sandbox v8.0.17

Running backup task (using bzip2 compression)
=============================================
bbr plugin starting up...
[bbr] 2019/02/07 13:19:56 INFO - Looking for scripts
[bbr] 2019/02/07 13:19:57 INFO - bosh/0/blobstore/backup
[bbr] 2019/02/07 13:19:57 INFO - bosh/0/blobstore/restore
[bbr] 2019/02/07 13:19:57 INFO - bosh/0/credhub/post-backup-unlock
[bbr] 2019/02/07 13:19:57 INFO - bosh/0/credhub/post-restore-unlock
[bbr] 2019/02/07 13:19:57 INFO - bosh/0/credhub/pre-backup-lock
[bbr] 2019/02/07 13:19:57 INFO - bosh/0/credhub/pre-restore-lock
[bbr] 2019/02/07 13:19:57 INFO - bosh/0/director/backup
[bbr] 2019/02/07 13:19:57 INFO - bosh/0/director/restore
[bbr] 2019/02/07 13:19:57 INFO - bosh/0/uaa/post-backup-unlock
[bbr] 2019/02/07 13:19:57 INFO - bosh/0/uaa/post-restore-unlock
[bbr] 2019/02/07 13:19:57 INFO - bosh/0/uaa/pre-backup-lock
[bbr] 2019/02/07 13:19:57 INFO - bosh/0/uaa/pre-restore-lock
[bbr] 2019/02/07 13:19:57 INFO - Running pre-checks for backup of 10.113.48.129...
[bbr] 2019/02/07 13:19:57 INFO - Starting backup of 10.113.48.129...
[bbr] 2019/02/07 13:19:57 INFO - Running pre-backup-lock scripts...
[bbr] 2019/02/07 13:19:57 INFO - Locking credhub on bosh/0 for backup...
[bbr] 2019/02/07 13:19:57 INFO - Locking uaa on bosh/0 for backup...
[bbr] 2019/02/07 13:19:57 INFO - Finished locking uaa on bosh/0 for backup.
[bbr] 2019/02/07 13:19:57 INFO - Finished locking credhub on bosh/0 for backup.
[bbr] 2019/02/07 13:19:57 INFO - Finished running pre-backup-lock scripts.
[bbr] 2019/02/07 13:19:57 INFO - Running backup scripts...
[bbr] 2019/02/07 13:19:57 INFO - Backing up blobstore on bosh/0...
[bbr] 2019/02/07 13:19:57 INFO - Finished backing up blobstore on bosh/0.
[bbr] 2019/02/07 13:19:57 INFO - Backing up director on bosh/0...
[bbr] 2019/02/07 13:20:01 INFO - Finished backing up director on bosh/0.
[bbr] 2019/02/07 13:20:01 INFO - Finished running backup scripts.
[bbr] 2019/02/07 13:20:01 INFO - Running post-backup-unlock scripts...
[bbr] 2019/02/07 13:20:01 INFO - Unlocking uaa on bosh/0...
[bbr] 2019/02/07 13:20:01 INFO - Unlocking credhub on bosh/0...
[bbr] 2019/02/07 13:20:01 INFO - Finished unlocking uaa on bosh/0.
[bbr] 2019/02/07 13:20:01 INFO - Finished unlocking credhub on bosh/0.
[bbr] 2019/02/07 13:20:01 INFO - Finished running post-backup-unlock scripts.
[bbr] 2019/02/07 13:20:01 INFO - Copying backup -- 17M uncompressed -- from bosh/0...
[bbr] 2019/02/07 13:20:01 INFO - Copying backup -- 19G uncompressed -- from bosh/0...
[bbr] 2019/02/07 13:20:01 INFO - Finished copying backup -- from bosh/0...
[bbr] 2019/02/07 13:20:01 INFO - Starting validity checks -- from bosh/0...
[bbr] 2019/02/07 13:20:02 INFO - Finished validity checks -- from bosh/0...
[bbr] 2019/02/07 13:21:08 INFO - Backup created of 00.000.00.000 on 2019-02-07 13:20:01.434753062 +0000 UTC m=+4.535478109
[bbr] 2019/02/07 13:21:08 INFO - Cleaning up...
1 error occurred:
error 1:
1 error occurred:
error 1:
Error streaming backup from remote instance. Error: ssh.Stream failed: stdout.Write failed: write 10.113.48.129_20190207T131957Z/bosh-0-blobstore.tar: no space left on device: ssh.Stream failed: stdout.Write failed: write 00.000.00.000_20190207T131957Z/bosh-0-blobstore.tar: no space left on device

it says no space left on device, but the bosh director have 300gb free space

**Comment by Klojo** [comment]
the solution is new version of the bbr client in the bbr addon

**Comment by jhunt** [comment]
bbr 1.4.0 has been added to the BBR Add-on BOSH Release, on origin.  I think you'll be in good shape once the pipelines vet the changes and we cut a new release.

**Comment by jhunt** [comment]
@Klojo try shield-addon-bbr-boshrelease v0.2.0: https://github.com/shieldproject/shield-addon-bbr-boshrelease/releases/tag/v0.2.0

It includes BBR 1.4.0.

**Comment by jhunt** [comment]
fixed the chmod issue in 0.2.0, with 0.2.1: https://github.com/shieldproject/shield-addon-bbr-boshrelease/releases/tag/v0.2.1

**Comment by jhunt** [comment]
This should be fixed in the 8.1.0 release, which should be out the door by next week (just in time for CF Summit Philly!)
