### ISSUE TITLE
Even though backup job is completed by an tenant operator, that operator cannot restore it through UI

### ISSUE THREAD

**Issue by SteveH-US** [starkandwayne/shield#491]
As an user with system role of "manager" and tenant role of "operator", I backed up a system using the WebUI. I can see that the system was successfully backed-up from the UI. However, when I attempt to "Restore data from backup", I'm told, through the WebUI, "This data system has never been backed up successfully.". 

But I can start the restore while viewing the BU log. However, the restore is not actually started.

**Comment by jhunt** [comment]
This sounds like a disconnect between the Restore wizard and the system detail page.  Given all the work in 8.1 (due out this coming week at CF Summit Philadelphia), I'd like to see if this is still an issue in that release.

I will try to reproduce this in my 8.0 and 8.1 labs.
