### ISSUE TITLE
[DOCKER] Server cannot contact the agent after regisration

### ISSUE THREAD

**Issue by zethis** [starkandwayne/shield#493]
**Problem:** Actually the shield agent does not send the IP to the Core,
In cause of the name of the network interface:
**eth0@if236** in my case
The Core cannot connect to the agent. (See Error log core-side)

agent.conf:
name: mongodb
authorized_keys_file: authorized_keys
host_key_file: id_rsa
listen_address: 0.0.0.0:5444
plugin_paths:
  - plugins
registration:
  url: http://shield:8080
  interval: 60

Agent Logs:INFO:  starting agent
DEBUG: pinging shield core
DEBUG: pre-registering with http://shield:8080/v2/agents as {"name":"mongodb","port":5444}
INFO:  pre-registered with http://shield:8080 as mongodb (port 5444)
DEBUG: POST /v2/agents returned [200 OK]

Server side logs:
ERROR:   [monitor] :5444: !! failed to run status op: dial tcp4 :5444: getsockopt: connection refused

**Solution?:**
Parse the all name of the network interface to get the Agent IP?

**Comment by zethis** [comment]
We found the problem, here is a Patch:
Same problem in S3 plugin

---
 core/v2.go                            | 2 +-
 plugin/s3/plugin.go                   | 4 ++++
 vendor/github.com/jhunt/go-s3/http.go | 2 ++
 3 files changed, 7 insertions(+), 1 deletion(-)

diff --git a/core/v2.go b/core/v2.go
index ddebe04..d63e42b 100644
--- a/core/v2.go
+++ b/core/v2.go
@@ -1093,7 +1093,7 @@ func (core *Core) v2API() *route.Router {
 
 		peer := regexp.MustCompile(`:\d+$`).ReplaceAllString(r.Req.Header.Get("X-Forwarded-For"), "")
 		if peer == "" {
-			peer := regexp.MustCompile(`:\d+$`).ReplaceAllString(r.Req.RemoteAddr, "")
+			peer = regexp.MustCompile(`:\d+$`).ReplaceAllString(r.Req.RemoteAddr, "")
 			if peer == "" {
 				r.Fail(route.Oops(nil, "Unable to determine remote peer address from '%s'", r.Req.RemoteAddr))
 				return
diff --git a/plugin/s3/plugin.go b/plugin/s3/plugin.go
index 2bf1bd5..935e212 100644
--- a/plugin/s3/plugin.go
+++ b/plugin/s3/plugin.go
@@ -551,6 +551,10 @@ func (e s3Endpoint) Connect() (*s3.Client, error) {
 		protocol = u.Scheme
 		host = u.Host
 	}
+	//Fixe if u.Host is empty
+	if host == "" {
+		host = e.Host
+	}
 
 	if e.Port != "" {
 		host = host + ":" + e.Port

**Comment by jhunt** [comment]
d'oh!  There goes Go, lulling me into a pattern of using `:=`, even when I should not.

**Comment by jhunt** [comment]
Looking at the v8.1.x branch (which, sometime before CF Summit (next week) will become the new master branch), I don't see evidence of the second problem, probably owing to rewrites and out-of-band fixes found during the 8.1 sprints.  I do see evidence of the first problem, but the issue has already been patched.  I'll keep this issue open until we officially release 8.1.0

**Comment by jhunt** [comment]
@zethis have you had a chance to try out 8.1.x releases?

**Comment by zethis** [comment]
@jhunt i'm on it right now, give feedback ASAP

**Comment by jhunt** [comment]
how did it go, @zethis ?

**Comment by zethis** [comment]
Fixed with v8.2 <3
