### ISSUE TITLE
Cannot login after clean install of shield Release v8.1.0 (non-BOSH)

### ISSUE THREAD

**Issue by zethis** [starkandwayne/shield#500]
After fixing shield-schema creation to v5 from v7. 
(Shield not starting if v5 schema not specified: ERROR: shield core failed to run: database failed schema version check: wrong schema version (7, but want to be at 5))

I'm not able to login (the page reload) and i get this error:
DEBUG: GET /v2/events responding with HTTP 404, payload [{"error":"SHIELD API endpoint `GET /v2/events' not found"}]

**Comment by jhunt** [comment]
I'm a little concerned that you needed to correct the `shield-schema` version, since that should be correct (schema v7, in 8.1.0).  A clean deploy, using this manifest (https://github.com/starkandwayne/shield-boshrelease/blob/master/manifests/shield.yml) works for me, and when I get on-box via a `bosh ssh`, I can verify schema:

```
shield/a84bcb81-f267-4b89-b40f-421e740638ff:~# /var/vcap/packages/sqlite3/bin/sqlite3  /var/vcap/store/shield/shield.db
SQLite version 3.24.0 2018-06-04 19:24:41
Enter ".help" for usage hints.
sqlite> select * from schema_info;
7
```

Can you sha1sum the following files?
```
shield/a84bcb81-f267-4b89-b40f-421e740638ff:~# sha1sum /var/vcap/packages/shield/bin/*
10b8aef7b45ec18ed06e0e032f001fb82c152d68  /var/vcap/packages/shield/bin/shield
9a53455eacb274dfb467035afa7f982e1b005f5b  /var/vcap/packages/shield/bin/shield-agent
34974fa621030ecb0534e6243e232b7ba5b0a9d5  /var/vcap/packages/shield/bin/shield-crypt
0a90f8a5b30947d5b8c12e36d17b7cfb68359480  /var/vcap/packages/shield/bin/shieldd
806ed7385cd05f521be0fbff3a56eb71ceae3973  /var/vcap/packages/shield/bin/shield-pipe
36166ddb6dd159b5704d917174c19e0d81248072  /var/vcap/packages/shield/bin/shield-recover
6a34ea0ef40b98a8b699568e5a35ef9e74d28c32  /var/vcap/packages/shield/bin/shield-report
b54db2bf8f1a429bc43958f274734b2ba7e4e0c3  /var/vcap/packages/shield/bin/shield-restarter
123a099d1d5948947b911d1105e605abdfa096e8  /var/vcap/packages/shield/bin/shield-schema
```

**Comment by zethis** [comment]
Right now i'm using docker, but here the sha1:
10b8aef7b45ec18ed06e0e032f001fb82c152d68  shield
9a53455eacb274dfb467035afa7f982e1b005f5b  shield-agent
34974fa621030ecb0534e6243e232b7ba5b0a9d5  shield-crypt
0e36285965b0c4d29fd452b7e55cc0b6d99e3588  shieldd
806ed7385cd05f521be0fbff3a56eb71ceae3973  shield-pipe
36166ddb6dd159b5704d917174c19e0d81248072  shield-recover
6a34ea0ef40b98a8b699568e5a35ef9e74d28c32  shield-report
b54db2bf8f1a429bc43958f274734b2ba7e4e0c3  shield-restarter
123a099d1d5948947b911d1105e605abdfa096e8  shield-schema

**Comment by zethis** [comment]
So at this time i'm using this repo:  https://github.com/starkandwayne/shield, and this tgz:
https://github.com/starkandwayne/shield/releases/download/v8.1.0/shield-server-linux-amd64.tar.gz
Not the bosh-release

**Comment by jhunt** [comment]
Try the official Docker image `shieldproject/shield:8.1.0` (https://hub.docker.com/r/shieldproject/shield).  There's a Docker Compose recipe in at https://github.com/starkandwayne/shield/blob/master/docker-compose.yml you can take cues from.
