### ISSUE TITLE
SHIELD Master Password red box doesn't go away when correct password given

### ISSUE THREAD

**Issue by thomasmitchell** [starkandwayne/shield#502]
**Is your feature request related to a problem? Please describe.**
The master password enter dialogue isn't dismissed when the correct password is given and the SHIELD is unlocked

**Describe the solution you'd like**
It should go away when the SHIELD is unlocked.

**Describe alternatives you've considered**
...refreshing the page after each submission?

**Comment by thomasmitchell** [comment]
I cannot replicate this. This may be a race condition, or it may be browsery-weirdness.

**Comment by jhunt** [comment]
Closing this as we could not reproduce the original aberrant behavior.  Please re-open if you find a way to reproduce.  Thanks!
