### ISSUE TITLE
[BUG] There is a restore button for purged archives

### ISSUE THREAD

**Issue by thomasmitchell** [starkandwayne/shield#506]
**Describe the bug**
The web UI has a restore button next to archives that have been purged.
I do not know what happens if you click it.

**To Reproduce**
1. Have one of your last four archives for a system be purged
2. Go to the Web UI page for that data system
3. Look at the archives

**Expected behavior**
It should _not_ have a restore button

**Screenshots**
![image](https://user-images.githubusercontent.com/12000017/57103996-3e542500-6cf5-11e9-8a0b-a889f862fecc.png)

**SHIELD versions (please complete the following information):**
 - SHIELD Core: 8.1.0

**Browser version(s) (please complete if reporting a web UI bug):**
 - OS: Windows
 - Browser: Firefox
 - Version: 66.0.3

**Additional context**

**Comment by jhunt** [comment]
Fixed.

<img width="819" alt="Screen Shot 2019-05-14 at 8 44 26 AM" src="https://user-images.githubusercontent.com/20047/57698834-84c64f80-7624-11e9-822b-e0b64852974c.png">
