### ISSUE TITLE
[BUG] Archives and Storage Used can go negative

### ISSUE THREAD

**Issue by thomasmitchell** [starkandwayne/shield#507]
**Describe the bug**
The status bar reports the number of archives and storage usage as negative

**To Reproduce**
No idea

**Expected behavior**
Actual representative numbers

**Screenshots**
![image](https://user-images.githubusercontent.com/12000017/57104354-1913e680-6cf6-11e9-96f2-574c479c9e3f.png)

**SHIELD versions (please complete the following information):**
 - SHIELD Core: 8.1.0

**Browser version(s) (please complete if reporting a web UI bug):**
 - OS: Windows
 - Browser: Firefox
 - Version: 66.0.3

**Additional context**
This happened after
1. Upgrading from 8.0.15 to 8.1.0 directly
2. Where the deployment had hundreds of stalled (pending) backups.
3. And all existing backups were older than the retention timeouts and therefore may have
already been purged.

**Comment by jhunt** [comment]
Looking at the raw data from the affected system, there are a lot of purged archives, and a lot of the associated tasks are either failed or still in the `scheduled` state.

We may want to prioritize the generic task interface in the Web UI, to aide in diagnosing this one _in situ_

**Comment by jhunt** [comment]
I think, for now, our best way forward is to either use a fixup, or a boot task, to reset the storage analytics on a per-store and per-tenant basis, using the data available in the database.  I _think_ this is related to bugs in bygone versions of SHIELD, and will need to gather more detail from the customer site to assist in the search.

Will touch base with @thomasmitchell next week when he gets back from vacation.

**Comment by thomasmitchell** [comment]
This may be "fixed". The root cause may have been the migration to 8.2, with a problem with archive purging being in process but not finished - the problem of jobs stalling is fixed, and the fixme gets rid of the orphaned archives.
