### ISSUE TITLE
[NEW] Vault plugin should support KV v2

### ISSUE THREAD

**Issue by thomasmitchell** [starkandwayne/shield#508]
**Is your feature request related to a problem? Please describe.**
Our Vault is KV v2. The plugin 404s when attempting to read from it because its trying to back it up like it is KV v1.

**Describe the solution you'd like**
Support both KV v1 and KV v2 seamlessly. Basically, bump the safe library that is vendored and then tie in to the function changed that occurred.

**Describe alternatives you've considered**

**Comment by jhunt** [comment]
Fixed in #513 (now merged)
