### ISSUE TITLE
Archives created without a restore key should be marked as invalid

### ISSUE THREAD

**Issue by qanx** [starkandwayne/shield#55]
In the shielddb:

```
shielddb=# SELECT * FROM archives;
                 uuid                 |             target_uuid              |              store_uuid              | store_key |  taken_at  | expires_at | notes | purge_reason
 | status
--------------------------------------+--------------------------------------+--------------------------------------+-----------+------------+------------+-------+-------------
-+--------
 17e2b6b8-e427-4726-a2eb-fe916fbf64b8 | 15993168-0419-4811-82b6-9a5959bbb508 | d9402c2a-7b0d-4325-b680-174c7b5f08f4 |           | 1453395676 | 1484931676 |       |
 | valid
 15b55b49-ddf4-4cbf-8a3c-b75cc4a47620 | 15993168-0419-4811-82b6-9a5959bbb508 | d9402c2a-7b0d-4325-b680-174c7b5f08f4 |           | 1453397886 | 1484933886 |       |
 | valid
(2 rows)
```

Currently when attempting to restore the archive this does not result in an error, e.g.:

```
$ shield restore archive 17e2b6b8-e427-4726-a2eb-fe916fbf64b8
Scheduled immedate restore of archive '17e2b6b8-e427-4726-a2eb-fe916fbf64b8'
```

* Archives created with empty store_key's should be marked as invalid
* Attempting to restore an invalid archive should error, client side
* Restrict listing of archives to valid archives only, unless `--invalid` is specified (new flag)
* New command: `purge invalid archives` to delete everything that is invalid

**Comment by geofffranks** [comment]
I don't think `shield purge invalid archives` is necessary. If we add this logic to the current purging cycle, the shield-daemon will automatically purge archives every X minutes if they match any of the purge-able criteria.

**Comment by geofffranks** [comment]
Investigated this, and there is no checking prior to creating an archive that restore key was actually set. 

We shouldn't auto-purge this, since purge requires a restore key, and will then fail. Instead we should prevent these from going into the database, and mark the corresponding task as failed, and refusing to create an archive record in the DB to begin with
