### ISSUE TITLE
Add owner to restore tasks

### ISSUE THREAD

**Issue by geofffranks** [starkandwayne/shield#64]
The owner of a restore task gets set to 'anon'. Ad-hoc backup tasks are set to the user running the backup. We should propagate this in for ad-hoc restore tasks as well.

```UUID                                   Owner      Type      Remote IP          Status   Started                           Stopped
====                                   =====      ====      =========          ======   =======                           =======
85f93041-5c56-4eaa-8577-2e43940e0d48   anon       restore                      done     Mon, 25 Jan 2016 14:44:11 +0000   Mon, 25 Jan 2016 14:44:16 +0000
67c2d46c-0adb-411a-9af3-9864f3c414f4   gfranks@   backup    10.72.72.21:5444   done     Mon, 25 Jan 2016 14:37:50 +0000   Mon, 25 Jan 2016 14:37:52 +0000```

**Comment by jhunt** [comment]
Looks like restore is broken in more ways than just this.  Like, `--to` doesn't work and using `--target` (which is the wrong flag) sends the UUID *as* the JSON payload.  Also also, there is no error checking on the JSON decodes, server-side, which is seriously bad juju.

**Comment by jhunt** [comment]
#78 to address the JSON problems, which I suspect will open up a whole host of other issues (some of them with restore)
