### ISSUE TITLE
Restore CLI improvements

### ISSUE THREAD

**Issue by geofffranks** [starkandwayne/shield#65]
1. It would be nice to alias `shield restore` to `shield restore archive`, similar to what we do with `list policies` and `list retention policies`. 
2. If no archive uuid is provided in a restore command, query the API and get a list of valid archives for restore, for the end user to choose.

**Comment by jhunt** [comment]
`shield restore` should do the following:

1. Ask for a job name / search pattern via a `tui.Form`
2. Show matching jobs in a `tui.Menu`
3. When they pick a job, list the most recent N (10?) valid archives, newest first, in a `tui.Menu`
4. When they pick an archive, restore that.

`shield restore <something>` should do the following:

1. Check if `<something>` is a valid UUID.  If so, restore that and exit
2. Search for jobs matching `<something>`, and display in a `tui.Menu`
3. When they pick a job, list the most recent N (10?) valid archives, newest first, in a `tui.Menu`
4. When they pick an archive, restore that.
