### ISSUE TITLE
shield list tasks --all handles pending/uncompleted tasks poorly

### ISSUE THREAD

**Issue by geofffranks** [starkandwayne/shield#80]
If there are pending tasks in `shield list tasks --all`, they show up with a `Started` field of `(pending)`, and a `Stopped` field of `(running)`. Seems impossible for un-started jobs to be running, we probably need to change this wording to `(not yet started)` under the `Stopped` column, but only for pending tasks. 

```
$ shield list tasks --all | head
UUID                                   Owner      Type     Remote IP           Status     Started                           Stopped
====                                   =====      ====     =========           ======     =======                           =======
106bf8a7-84d1-4673-8b53-fe933300e6db   gfranks@   backup   10.244.3.46:5444    pending    (pending)                         (running)
```

**Comment by jhunt** [comment]
@thomasmmitchell can this be closed now?

**Comment by thomasmmitchell** [comment]
@jhunt Methinksso
