### ISSUE TITLE
Support read-replicas for the mysql plugin

### ISSUE THREAD

**Issue by geofffranks** [starkandwayne/shield#96]
Since mysqldump locks tables when backing up by default, it would be useful to provide support for
a read-only-replica to be used for backing data up.

- Add a `mysql_read_replica` property to the endpoint configuration - optional
- If `mysql_read_replica` is specified, use that host during the Backup() call. If it is not specified, use the `mysql_host`
- When restoring, use `mysql_host` all the time, and ignore `mysql_read_replica`

**Comment by soutenniza** [comment]
https://github.com/starkandwayne/shield/pull/107
